### ISSUE TITLE
Feature Request Usability: Keep Dropdown positioned when Cmd / Ctrl clicking OR/AND keep filter after selecting with Ctrl / Cmd

### ISSUE THREAD

**Issue by Skeeve** [harvesthq/chosen#2890] opened 2017-09-30 06:33 UTC
Use case: I have a long list of similar looking entries in my options. Sometimes I want to select several of those entries.

So what I do is, I enter a filter and select the first of the entries, having Cmd pressed.

What I get is the entry. But the filter is gone. Additionally the dropdown is positioned at the beginning.

It would be good if at least the filter would be kept. Would the dropdonw remain positioned it would be great.

### Steps to reproduce

How to reproduce this issue on https://harvesthq.github.io/chosen/.

  1. Enter a filter into the Multiple Select of a country (e.g. "g")

  2. select one of the options while holding cmd (or ctrl) (e.g. Guam) 

  3. Filter gets replaced by the selected entry. Options list is repositioned.

### Expected behavior

In the example above "Guam "should still be displayed. The filter should be kept so that you could add Guatemala now.

### Actual behavior

Instead Guam is now a selected country and the option list is unfiltered at the top and you can select United Kingdom or United States ;)

### Environment

  - **Chosen Version - **: 1.8.2

  - **jQuery or Prototype Version - **: jQuery 1.10 here. Don't know which one you have

  - **Browser and Version - **: FireFox 52.01 / Safari 11.0

  - **OS and Version - **: macOS 10.12

### Additional information

I discovered chosen just yesterday and already love it. Thanks a lot for it.

**Comment by tjschuck** [comment] 2017-10-02 18:37
Closing this as a duplicate of #2888 — please leave any additional feedback you have there.  Thanks!

**Closed by tjschuck** 2017-10-02 18:37 UTC
