### ISSUE TITLE
Add an option when one is not found

### ISSUE THREAD

**Issue by horphoz** [harvesthq/chosen#2465] opened 2015-10-30 01:06 UTC
Add a config option to allow the user to add and auto-select a new option.

For example: a select has only two color options: red, and green.
If the user types blue, chosen could keep saying "no results match blue...", but it also could give the option to add what the user typed in the select options (in this case "blue").

You could also specify a prefix like "_new_", so the option could be something like:
<option value="_new_blue">blue</option>

**Comment by tjschuck** [comment] 2015-10-30 16:00
This is a duplicate of https://github.com/harvesthq/chosen/pull/166 -- please leave any additional feedback you have there.  Thanks!

**Closed by tjschuck** 2015-10-30 16:00 UTC
