### ISSUE TITLE
possible to have list items entered as "free" strings - not from a bond list?

### ISSUE THREAD

**Issue by mbarmettler** [harvesthq/chosen#2887] opened 2017-09-22 14:02 UTC
Hi guys,

### Steps to reproduce
i actually search for a possiblity to have any string able to be enter in the box.

### Expected behavior
init from List<complextype> (pre-set on view load)
post on submit - write back the items from box to ViewModel property list

### Environment
  -  current component vers.
  - jquery 3.1.1
  - Chrome 65
  - Win 10, 64bit

### Additional information

i tried to reach the requirement with Tag-It control which uses Jquery-ui - but its not really compatible with the ASP.net MVC framework as far i can tell....

Thanks & best regards
M

**Comment by tjschuck** [comment] 2017-09-22 19:00
It sounds like you're talking about https://github.com/harvesthq/chosen/pull/166 — that's a long-standing request, but not currently baked into Chosen.  Closing this as a duplicate of that — feel free to leave any additional feedback you have there!

**Closed by tjschuck** 2017-09-22 19:00 UTC
