### ISSUE TITLE
Does not work on inactive tabs

### ISSUE THREAD

**Issue by markus-s24** [harvesthq/chosen#2466] opened 2015-10-30 14:26 UTC
I am using Bootstrap tabs via data-toggle="tab". $(".chosen-select").chosen() does not create the Chosen selects for selects in tab-divs that are not "active".

    <ul class="nav nav-tabs">
       <li class="active"><a data-toggle="tab" href="#tab1">Tab 1</a></li>
       <li><a data-toggle="tab" href="#tab2">Tab 2</a></li>
    </ul>
    <div class="tab-content">
       
       <div id="tab1" class="tab-pane fade in active">
          <select class="chosen-select" multiple="multiple">
             ...
          </select>  
       </div>
       
       <div id="tab2" class="tab-pane fade in">
          <select class="chosen-select" multiple="multiple">
             ...
          </select>
       </div>
    </div>

My current workaround is to make all tabs active on load and disable them via javascript after Chosen did its work.

**Comment by tjschuck** [comment] 2015-10-30 16:01
I think this is a duplicate of #2332 -- please try the workaround there.

**Closed by tjschuck** 2015-10-30 16:01 UTC
