### ISSUE TITLE
Place holder does not re-appear once all selected items have been deselected. 

### ISSUE THREAD

**Issue by cderees** [harvesthq/chosen#2513] opened 2016-01-24 13:16 UTC
Using chosen.jquery.js Version 1.4.2 I'm trying to code a solution which will provide ability to deselect all previously selected items and set re-instate the inital placeholder trying the following without much success. 

I am able to remove / deselect selected items using 

```javascript
$("#CompanyAtrributes").val('').trigger("chosen:updated");  
```

however I stuggle to the place holder to re-appear. 

Thank you in advance if you are able to help. 

```javascript
function resetMultiSelection(){
$("#CompanyAtrributes").val('').trigger("chosen:updated");
$("#CompanyAtrributes").trigger("chosen:updated");	
$("#CompanyAtrributes").data("chosen").default_text = "Please Select..."
}
```

```html
<select name="CompanyAtrributes" id="CompanyAtrributes" data-placeholder="Company Attributes" multiple class="chosen-select-width" tabindex="16" >
            <option value=""></option>
            <option>Quantitative</option>
            <option>Qualitative</option>
            <option>Technology</option>
            <option>Healthcare</option>
          </select>
```

**Comment by koenpunt** [comment] 2016-02-24 17:36
Thanks for reporting.

NB. This is only the case when programmatically clearing the value.

**Comment by ComeBurguburu** [comment] 2016-03-02 14:52
Select is multiple
try 
``````````````````````````````````````````````````````````````````````````````````js
$("#CompanyAtrributes").val([]).trigger("chosen:updated");  
``````````````````````````````````````````````````````````````````````````````````
instead

**Comment by pfiller** [comment] 2016-06-07 21:31
Duplicate of #1679

**Closed by pfiller** 2016-06-07 21:31 UTC
Labels: Bug
