### ISSUE TITLE
Suggestion: tags

### ISSUE THREAD

**Issue by mathritter** [harvesthq/chosen#2839] opened 2017-06-20 19:16 UTC
Just a suggestion:
Allow tagging support, multiple or single. So people can add options on demand, would be very useful.

**Comment by Mikk3lRo** [comment] 2017-10-02 08:53
Duplicate of:
https://github.com/harvesthq/chosen/issues/2848
https://github.com/harvesthq/chosen/issues/2895

**Closed** 2017-10-08 21:02 UTC
