### ISSUE TITLE
In the Multiple Select search does not working properly

### ISSUE THREAD

**Issue by dmitrystas** [harvesthq/chosen#2856] opened 2017-07-28 07:42 UTC
Hello. On the demo https://harvesthq.github.io/chosen/ in Multiple Select I try find country French Southern Territories

1. start typing "french southern t" - all is ok - https://prnt.sc/g1b87t

2. start typing from second word "southern" - all is ok - https://prnt.sc/g1b8br

3. but if I continue and type "southern t" - no result found - https://prnt.sc/g1b8gf

**Comment by tjschuck** [comment] 2017-07-28 18:54
This is a well-known issue, and is a duplicate of/would be fixed by #1483.

Thanks for reporting — please leave any additional information you have on that ticket!

**Closed by tjschuck** 2017-07-28 18:54 UTC
