### ISSUE TITLE
[Vietnamese] Can not search text vietnamese with keyword not diacritics

### ISSUE THREAD

**Issue by conghau** [harvesthq/chosen#2652] opened 2016-07-21 03:41 UTC
Can not search text vietnamese with keyword not diacritics

### Steps to reproduce

Tell us how to reproduce this issue.

Example:

1.> I create new select with content is vietnamese language
<select>
  <option value="1">02.01 Hướng dẫn KH UT</option>
  <option value="2">02.02 Cập nhật số tài khoản ngân hàng</option>
  <option value="3">02.03 KH yêu cầu huỷ giao dịch UT</option>
  <option value="4">02.04 KH báo chưa nhận được tiền</option>
  <option value="5">02.05 KH soạn UTVQ nhưng chưa liên hệ</option>
  <option value="6">02.06 Hạn mức KH không đủ để UT</option>
</select>

2.> . I search with keyword "so tai khoan", "yeu cau", ...etc.. (not diacritics)

3.  Chosen search not found

Link demo : http://jsfiddle.net/oj3cjw9w/180/

I had fix this.

**Comment by tjschuck** [comment] 2016-07-21 20:32
This is a duplicate of https://github.com/harvesthq/chosen/issues/536 — please leave any additional feedback you have there.

There is also a PR here that attempts to fix this: https://github.com/harvesthq/chosen/pull/2618 — feel free to use that fork in the meantime if you'd like to work around this yourself.

**Closed by tjschuck** 2016-07-21 20:32 UTC
