### ISSUE TITLE
Select in a div that's hidden on page load

### ISSUE THREAD

**Issue by MK-Chris** [harvesthq/chosen#2309] opened 2015-04-09 14:00 UTC
Hi

I seem to have hit an issue using Chosen to generate a select list in a div element that's hidden on page load.  If the div is then shown, the select list has no width and you can't see any item text.  You should be able to see what I mean with the below JSFiddle:

http://jsfiddle.net/mamwuen5/

![2015-04-09_14-57-14](https://cloud.githubusercontent.com/assets/6383306/7068234/e58d19a4-dec8-11e4-8b12-3f2777605a05.png)

If the div is *not* hidden on page load, you can hide and show it to your heart's content, as in the below JSFiddle:

http://jsfiddle.net/mamwuen5/2/

Am I doing something wrong, or is this a bug?

Thanks

Chris

**Comment by ComeBurguburu** [comment] 2015-04-09 15:25
solved like that : 
http://jsfiddle.net/mamwuen5/5/

add width: auto

**Comment by briannesbitt** [comment] 2015-04-09 21:55
For what its worth I just came across this having a chosen select in a bootstrap modal.

Fixed it by using `$("select").chosen({width: "100%"}); ` option.

**Comment by MK-Chris** [comment] 2015-04-10 10:38
Thank you - I was hoping to have it use the width specified in the CSS, which is why it wasn't specified (as I have selects of differing sizes sometimes), but I can try and work around that.

**Comment by chameeya** [comment] 2015-11-05 22:55
This is probably the most annoying "feature" of this control. I tried Select2 and it doesn't have this limitation. 

What I did was something akin to 
 $('.droplist').each(function(){
    var css_width = $(this).css("width");
    $(this).chosen({width: css_width});
}

which works okay for me.

**Comment by alar1** [comment] 2016-01-18 10:05
this whorks for me:
$(".chosen-select").chosen('destroy');
$(".chosen-select").chosen({width: "100%"});

**Comment by pfiller** [comment] 2016-06-02 22:37
Duplicate of #92

**Closed by pfiller** 2016-06-02 22:37 UTC
