### ISSUE TITLE
How can save entered value, if not available in dropdown

### ISSUE THREAD

**Issue by uistacks** [harvesthq/chosen#3023] opened 2018-09-27 12:12 UTC
I have a functionality like Country/State/City.

Suppose if user enter a city name, but the city name is not available in dropdown, then we need to save that city in database to show in dropdown from next time.

is this possible. please suggest me solutions..

**Comment by sanjay-russmediatech** [comment] 2018-10-02 07:07
looks like what I searching for waiting for reply from someone :)

**Comment by tjschuck** [comment] 2018-10-02 14:52
This is not currently supported in Chosen, and is a long standing request — see https://github.com/harvesthq/chosen/pull/166 for the canonical issue about this.

Closing this as a duplicate of that.

**Closed by tjschuck** 2018-10-02 14:52 UTC
