### ISSUE TITLE
&nbsp; appearing in Chosen search results

### ISSUE THREAD

**Issue by chrisdeeming** [harvesthq/chosen#2586] opened 2016-03-31 20:48 UTC
I wanted this issue to get more exposure because there doesn't appear to currently be an open issue for it.

The last issue related to this was closed: #2274.
This appears to be a regression of #1707.

The issue is that if you search for n, b, s or p it will return search results for any options that contain &nbsp;

Here's a fiddle: https://jsfiddle.net/o2ajt5cb/

**Comment by pfiller** [comment] 2016-06-07 21:37
This only affects Chosen with `search_contains` applied. Duplicate of #2548.

**Closed by pfiller** 2016-06-07 21:37 UTC
