### ISSUE TITLE
Tapping the multiple select box again on iPad does not re-activate .chosen-drop div

### ISSUE THREAD

**Issue by jeffkee** [harvesthq/chosen#2592] opened 2016-04-11 23:55 UTC
On iPad, the multiple select will hide the dropdown after one item is selected. To re-enable the dropdown for more selections, the only option is to hit the space key, tapping the input area does not show the chosen-drop again. 

[Chosen demo page](http://harvesthq.github.io/chosen/) shows this issue on the iPad already.

### Expected behavior
Ideally another tap should enable the chosen-drop again... or not even hide it upon selecting element only. Wait until the user taps away from the element. 

### Environment

1.5.1 Chosen V,

**Comment by pfiller** [comment] 2016-06-07 04:14
Duplicate of #2289

**Closed by pfiller** 2016-06-07 04:14 UTC
