### ISSUE TITLE
Scrolling issue with jQuery 2.2.0

### ISSUE THREAD

**Issue by sarojanand** [harvesthq/chosen#2519] opened 2016-01-28 16:58 UTC
Testing Chosen for the first time and notice that it works fine with jQuery 1.6.4 as the website uses its examples. But it has some issue with jQuery 2.2.0. When user taps in the search box or selects an item from a Standard Select list, the browser scrolls rapidly to the page footer (always). I have tested in Chrome as well as IE 11.

Any suggestions very welcome. Thanks!

**Comment by tjschuck** [comment] 2016-01-28 17:09
@sarojanand Thanks for your report!  This is actually a duplicate of https://github.com/harvesthq/chosen/issues/2506 — please feel free to leave any additional feedback you have there.

Thanks again!

**Closed by tjschuck** 2016-01-28 17:09 UTC
