### ISSUE TITLE
Chosen on Ipad scroll problem single select en click problem multiple select

### ISSUE THREAD

**Issue by donthebike** [harvesthq/chosen#2289] opened 2015-03-28 18:44 UTC
The recent fix:
#2119 Fix touch event propagation
seems to breaks other functionality of chosen on Ipad (tested in Ipad 3, latest version chosen).
Problems:
 - single select: scroll of dropdown list does not work any more
 - multiple select: removing selected items is impossible and after the first time a click in the select window does not show the drop down list
These problems can be reproduced using an Ipad on the standard chosen test site: http://harvesthq.github.io/chosen/  on the Standard select and Multiple select examples.
They probably have to do with the #2119 Fix as the functionality was ok before.

**Comment by canaandavis** [comment] 2015-03-31 20:29
I am also experiencing the issue @donthebike is seeing.

**Comment by damianthepichler** [comment] 2015-04-09 13:14
Same here

**Comment by ksidibe** [comment] 2015-04-13 17:28
Same problem here. Both on IOS and Android

**Comment by dakhran** [comment] 2015-04-14 16:36
Also seeing this issue.

**Comment by AmirS2** [comment] 2015-04-28 15:36
Same issue here regarding the deselect icon (the cross) not working to remove selected options on touch devices. The backspace key does still work to remove options though.

I have tested before / after the #2119 fix (using git bisect) to confirm that the issue was introduced by that commit. Tested on Safari and Chrome on iPad, and also Chrome on Android tablet.

**Comment by frahugo** [comment] 2015-04-30 17:18
Same issue as @AmirS2.  But it did fix the click event when the screen scrolls while the dropdown opens.

**Comment by qwirkcreative** [comment] 2015-05-05 22:41
Same issue.

**Comment by nlaitchison** [comment] 2015-05-12 22:02
I was having the same issue plus a selecting issue on Android. I just went ahead and removed all touch events as an easy fix. Everything works for both Android and iOS except that when an option is selected it isn't initially highlighted on mobile devices. I am just using the single select though. I'm also not very experienced with touch events so I'm not sure if there was a specific reason they were used in this case?

**Comment by qwirkcreative** [comment] 2015-05-12 22:29
Oh, thanks! My team figured something out as well. We will probably update
the plugin when we find time. Not sure what our solution was in the end.

**Comment by tonvanalebeek** [comment] 2015-05-15 08:12
Same issue here

**Comment by vbanuelos** [comment] 2015-05-15 23:03
Im experiencing the same issue. I managed to find a work around, which involves commenting out the evt.preventDefault() on touchstart.chosen that was implemented with #2119

```js
      this.container.bind('touchstart.chosen', function(evt) {
        _this.container_mousedown(evt);
        //return evt.preventDefault();
      });
      this.container.bind('touchend.chosen', function(evt) {
        _this.container_mouseup(evt);
        return evt.preventDefault();
      });
```

**Comment by ptrussart** [comment] 2015-05-25 08:17
I also seeing this issue. Very annoying for mobile users.

Dear @vbanuelos, your workaround did not fix the issue for me. What version do you use ? 1.4.2 ?

**Comment by vbanuelos** [comment] 2015-06-04 23:03
@ptrussart -- that's correct. V 1.4.2

**Comment by noahsark769** [comment] 2015-06-05 22:16
Just thought I'd throw in my two cents! This is an issue for me also. My workaround was to just disable chosen on iPads, which you can do by changing line 532 of the jquery file from

```javascript
```

**Comment by annagl** [comment] 2015-06-30 02:41
Have the same scrolling issue, fix from @vbanuelos helped me, thanks!

**Comment by razvar** [comment] 2015-07-09 11:48
+1 fix from @vbanuelos . Thanks a lot. Tested on Safari and Chrome under iOS8.3 on a single select list.

**Comment by guushamann** [comment] 2015-10-05 13:42
fix from @vbanuelos helped me, thanks!

**Comment by sisiwei** [comment] 2015-10-30 20:28
Yes! +1 fix from @vbanuelos

**Comment by michaelblinn** [comment] 2015-11-30 16:13
Will this fix be re-merged or is there something blocking?

**Comment by jmelosegui** [comment] 2016-01-05 17:05
> Will this fix be re-merged or is there something blocking?

Something new about this?

**Comment by vbanuelos** [comment] 2016-01-05 17:48
@ptrussart -- It appears my workaround is working for most. Perhaps it can be implemented in the latest release?

**Comment by jmelosegui** [comment] 2016-01-05 18:09
Right now hard coded though. :(

**Comment by Meligy** [comment] 2016-05-12 05:32
Just got a colleague who had to hard to code the `preventDefault()` workaround mentioned above.

Is there a problem with this? I see a commit removing the line and a commit reverting the removal.

Thanks a lot.

**Comment by tatthien** [comment] 2016-05-31 02:38
@vbanuelos That's great

**Comment by dangyoungworld** [comment] 2016-06-02 04:44
Replace line 1004
`close_link.bind('click.chosen', function(evt) {`
by
`close_link.bind('touchstart.chosen click.chosen', function(evt) {`

**Comment by josemigueldel85** [comment] 2016-06-15 21:09
This works for me.

http://realize.be/mobile-support-chosen

**Comment by muntaserq** [comment] 2016-06-30 16:59
@josemigueldel85 this might be a stupid question, but where is the quick fix for mobile touch support intended to be put in? I'm talking about the below from your post above. 

```
// Chosen touch support.
    if ($('.chosen-container').length > 0) {
      $('.chosen-container').on('touchstart', function(e){
        e.stopPropagation(); e.preventDefault();
        // Trigger the mousedown event.
        $(this).trigger('mousedown');
      });
    }
```

**Comment by josemigueldel85** [comment] 2016-07-04 16:27
Download the file Attachment in the web page. http://realize.be/mobile-support-chosen

chosen.jquery.min_.js.txt

**Comment by ulumi** [comment] 2016-10-04 18:43
the fix works, but is applied to the 1.1 chosen file version... any ways to have a 1.4.1 version patched? or let us know what's been modified in it? thanks

**Closed** 2016-10-27 21:20 UTC
Labels: Bug, Has Solution

**Comment by kemni** [comment] 2017-02-09 12:16
@vbanuelos iam using this approach too on v1.6.1, and it works fine on ipad (chrome simulator), are there any consequences of this approach.

**Comment by Mr-Anonymous** [comment] 2017-02-15 15:37
I am having the same issue. Is there a way to add @vbanuelos approach without editing the source file? Like a hack that we can add to our own site's script instead of editing the `chosen.min.js` file directly? I have this issue on ipad where chosen is not scrollable even with current version.

**Comment by Mr-Anonymous** [comment] 2017-02-15 15:45
I see the chosen gets disabled in mobile phone but its not disabled in iPad. I think it will help if we can disable chosen in iPads and tablets altogether just like mobiles. Is there a way to do this?

**Comment by ksom** [comment] 2017-02-27 18:50
Hi everyone,

I'm experiencing this issue and I'm looking for a real fix.

Did you fixed it in any version? Do you have an ETA ? 

Should I upgrade chosen library?

@harvesthq/chosen-developers

Thanks per advance

**Comment by kemni** [comment] 2017-03-01 14:55
my fix worked for multi-select but it is disturbing single chosen select by
not letting them work in first click, then when you click second time the
select box works, so here is one of the pros and cons,

seems like problems only no solutions

**Comment by mcjwb** [comment] 2017-03-01 17:09
Sounds like this was fixed in master in October - #2725 (referenced above 9 Oct 2016). Or are you testing against master (and this fix) and it's still an issue?
There has yet to be a new release, but you can install the master version through bower with
 `bower install https://github.com/harvesthq/chosen.git#master --save` 
(if you already have version 1.6.2 installed it'll give you an option to overwrite the installed version). Not ideal, as every future `bower install` will get the very latest version, but an option for now.

**Comment by robhuska** [comment] 2017-03-24 19:57
I have done what @mcjwb recommended and used the master version. I typically use whatever is hosted on cdnjs.com, but that is broken still too. I will keep an eye for this to get fixed.

**Comment by koenpunt** [comment] 2017-03-24 20:34
Just released Chosen 1.7.0 which includes #2725

**Comment by mcjwb** [comment] 2017-03-28 08:13
Great, sorted everything for me. Thank you very much.

**Comment by le0pard** [comment] 2017-06-07 08:11
* single select: scroll of dropdown list does not work any more

Confirmed - fixed.

 * multiple select: removing selected items is impossible and after the first time a click in the select window does not show the drop down list

Still not fixed (chosen 1.7.0)

**Comment by krishan-kumar-mourya** [comment] 2017-07-04 07:40
Thanks @snakexxx 
`Replace line 1004 in file chosen.jquery.js
close_link.bind('click.chosen', function(evt) {
by
close_link.bind('touchstart.chosen click.chosen', function(evt) {`

replace all your` 'click.chosen'` events with `'touchstart.chosen click.chosen'`

**Comment by SivanKarthick** [comment] 2017-07-13 12:34
Hi,

Its Working!!!!
Please Replace your "chosen.JS" file into below txt to change the js
http://realize.be/files/chosen.jquery.min_.js.txt
