### ISSUE TITLE
Incorrect Tag for 1.4.2 bower-chosen

### ISSUE THREAD

**Issue by bluengreen** [harvesthq/chosen#2307] opened 2015-04-07 21:12 UTC
I would have added this issue on that repo except issues are not accepted on that repo. 

Notice the tags are incorrect on the repo. This is causing issues getting the correct version from bower since it relies on the tag to get the version. Also, 1.4.2 is the correct version to use if you want the css injected correctly with wiredep since the main object is correct for the files contained in the package.

https://github.com/harvesthq/bower-chosen/blob/v1.4.2/bower.json

**Comment by bluengreen** [comment] 2015-04-08 01:51
Please on https://github.com/harvesthq/bower-chosen/

git checkout master
git tag -d v1.4.2 
git push origin :refs/tags/v1.4.2
git tag -a v1.4.2 -m 'correct 1.4.2 tag'
git push --tags 

Yes please. :+1:

**Comment by tjschuck** [comment] 2015-07-17 16:10
@bluengreen Thanks for reporting!  I'm going to close this issue in favor of https://github.com/harvesthq/chosen/issues/2324 (which is a duplicate of this), but please feel free to leave any feedback you have over there.  Hopefully we'll get this fixed soon.

**Closed by tjschuck** 2015-07-17 16:10 UTC
