### ISSUE TITLE
A single select create two div

### ISSUE THREAD

**Issue by NecroSyri** [harvesthq/chosen#2603] opened 2016-05-18 15:24 UTC
With a single select, I end up with two div, one functionnal, and one with only one element inside, and not working.

  1. I have a select using chosen
![image](https://cloud.githubusercontent.com/assets/19432666/15364585/4db49942-1d1d-11e6-9080-08aacdeee0d3.png)

  2. I use a form validator from bootstrap : form-control

  3. After the first chosen selector, there's another one, but this one doesn't work
![image](https://cloud.githubusercontent.com/assets/19432666/15364613/676c9c4a-1d1d-11e6-96b5-6441ba66cff9.png)

### Environment

I use bootstrap, jquery 1.11.3, chosen 1.3.0
I'm on windows 7.
The bug happen only with chrome, not on firefox.

**Comment by tjschuck** [comment] 2016-05-18 19:44
Chosen 1.3.0 is about 1.5 years old — there have been a few releases since then.  Does it still happen on the [latest version](https://github.com/harvesthq/chosen/releases)?

Additionally, can you please link to a publicly accessible page (or a [Fiddle](http://jsfiddle.net)) that shows the issue so we can attempt to reproduce?

**Comment by pfiller** [comment] 2016-06-02 21:25
Closing until @tjschuck gets his answers!

**Closed by pfiller** 2016-06-02 21:25 UTC
