### ISSUE TITLE
Scrolling dropdown doesn't work on iPad

### ISSUE THREAD

**Issue by shaman197** [harvesthq/chosen#2732] opened 2016-10-19 08:02 UTC
**Expected behavior**
The dropdown list should scroll on iPad.

**Actual behavior**
The dropdown list didn't scroll at all.

**Environment**
- Chosen version 1.5.1 (also tested it on 1.6.2)
- JQuery version 1.11.4
- Safari version 602.1
- Mac OS X 10.1

I also tried the most current version in your website (https://harvesthq.github.io/chosen/) v1.6.2 but it still doesn't work, while the standaard select does work. I used the same iPad an webbrowser. I saw webkit-scrollbar & overflow is used. It's active, but doesn't work.

**Comment by koenpunt** [comment] 2016-10-19 10:32
Duplicate of #2289, and a solution is pending in #2725

**Closed by koenpunt** 2016-10-19 10:32 UTC
