### ISSUE TITLE
Why compass?

### ISSUE THREAD

**Issue by whmii** [harvesthq/chosen#2368] opened 2015-07-14 19:19 UTC
I'm currently using `chosen-rails` and am unable to update sass to the current version due to the use of compass in chosen. 

I am planning on putting a pr together this evening to remove it, but before I do I wanted to make sure there wasn't a super huge reason that yall were using compass (since it is no longer well maintained and conflicts so directly with current implementations of sass).

:beers:

**Comment by tjschuck** [comment] 2015-07-14 20:29
/cc @mlettini 

Also, Compass is no longer well-maintained?  Do you have any reference to it being abandoned by its maintainers to back that up?

**Comment by mlettini** [comment] 2015-07-14 21:01
> Also, Compass is no longer well-maintained? Do you have any reference to it being abandoned by its maintainers to back that up?

Also curious of this.

We are currently using Compass for `image-url` and any `@include`s. It's been in there awhile. While new browsers probably don't need vendor-prefixed gradients and box-sizing, older browsers and support still do. To be honest, I don't know if Chosen has any written browser requirements...

**Comment by tjschuck** [comment] 2015-07-14 21:04
@mlettini See [this code block](https://github.com/harvesthq/chosen/blob/910a12599c10a11b7005feedb1e53e4b4535100e/coffee/lib/abstract-chosen.coffee#L275-L282) -- anything that passes it is "supported".

The only desktop browser explicitly not supported is IE less-than 8.

**Comment by koenpunt** [comment] 2015-07-21 20:15
We could switch to node-sass, which uses libsass. Vendor prefixes could be handled by postcss' autoprefixer

**Comment by whmii** [comment] 2015-07-23 14:33
I think rails-sass would be fine. I'd imagine updating existing tech instead of introducing new ones.

**Comment by whmii** [comment] 2015-07-23 14:37
Also, I think that prefixing is better relinquished to a tool like Autoprefixer so that things like prefixing requirements do not effect the sass files themselves. this way you can write the code you want to write and the prefixing is done separately.

**Comment by whmii** [comment] 2015-07-23 15:15
Ah, I missed that yall were using grunt. I have posted a `wip` branch with some changes to the gruntfile. https://github.com/whmii/chosen/tree/wm-sass-rails

It doesn't seem to want to run any grunt commands right now. I'll debug in a bit.

**Comment by tjschuck** [comment] 2015-07-23 15:24
@whmii Actually, this all starts from this, right?

> am unable to update sass to the current version due to the use of compass in chosen.

Compass and Sass both are just _development_ dependencies for Chosen -- they're just necessary to build the final CSS from the lib's source.  But Chosen's dev dependencies shouldn't affect your ability to run any arbitrary version of Sass and/or Compass.

What problem specifically are you having?

**Comment by koenpunt** [comment] 2015-07-23 15:30
@whmii `image-url()` and other functions are not supported by `node-sass`. Although I've created a simple module to support `image-url`, `image-width` and `image-height`. And I planning to implement the other asset functions as well (`font-url` etc)

**Comment by whmii** [comment] 2015-07-23 17:33
Out of curiosity, why are you using the grunt for your stylesheets and not the asset pipeline, since that would allow `image-url`.
(not trying to call the whole app in to question here, sorry for all the nagging :disappointed_relieved:  )

**Comment by koenpunt** [comment] 2015-07-23 17:38
@whmii because using the asset pipeline  would make Rails a dependency of Chosen

**Comment by tjschuck** [comment] 2015-07-23 17:41
@whmii I think all of your issues are specifically with [chosen-rails](https://github.com/tsechingho/chosen-rails), not Chosen itself.  All of the dependency conflicts you seem to have are not related to Chosen itself -- its dependencies are just development dependencies.  Chosen itself is just some JS and CSS files and a couple of images.

Closing this -- feel free to open another issue over on chosen-rails if you're still having problems.

**Closed by tjschuck** 2015-07-23 17:41 UTC

**Comment by AlJohri** [comment] 2015-09-25 18:55
@koenpunt 

To aid in the transition away from compass and towards node-sass, perhaps you can use http://bourbon.io/, a "simple and lightweight mixin library for Sass".

All of the mixins being used in the code: `box-sizing`, `user-select`, `background`, and `background-image` are already included in bourbon:

- bourbon/bourbon-deprecated-upcoming => box-sizing
- bourbon/css3/user-select => user-select
- bourbon/css3/background => background-image
- bourbon/css3/background-image => background-image

I simply added `@import "bourbon/bourbon";` to the top of my `chosen.scss` file and the sass is compiling just find and rendered content looks identical save the `image-url` issue mentioned above.

**Comment by raldred** [comment] 2015-10-03 17:01
So as @koenpunt closed my issue and this issue is closed, does that mean harvesthq have deemed this issue wont fix?
You only have to look at their repos of late, they're in a sorry state, failing builds, few commits.

**Comment by tjschuck** [comment] 2015-10-05 16:16
@raldred If you read through this issue, you'll see that it was closed as wontfix because there's no problem with Compass in Chosen.  Compass is strictly a dev dependency, and it works just fine to generate the final product.  Chosen itself is just some JS and CSS files plus a couple of images.

If you're having issues with Compass and Rails, then your issues are with Compass and Rails, not Chosen.  If you're using [chosen-rails](https://github.com/tsechingho/chosen-rails), please note that that is a third-party project, and you should open an issue there if you have one with it.

If you download the [release version of Chosen](https://github.com/harvesthq/chosen/releases), you can include it in your project as-is and not be concerned with Compass at all, which is again just a development dependency of Chosen.

As for the "sorry state" of this and other repos, I can only point you to the [license for Chosen](https://github.com/harvesthq/chosen/blob/4b03346635d59ca6028ca267590b84354b8eead4/LICENSE.md), which is very explicit in pointing out that this software is provided as-is with no guarantee of _anything_.  It also gives you permission to fork the source and do whatever you so desire, including removing the Compass dependency.  The source was given to you freely to use as-is, or to modify however you'd like.

I'd like to remind you that all of the maintainers of Chosen fill that role voluntarily and as time allows. None of the maintainers is employed to work on open-source software full time. We all have other responsibilities (and lives!).  We are also all real-life people who are saddened when people describe our work that we have provided freely and generously as being in a "sorry state".  Please have some empathy and realize that there are humans with needs, wants, and dreams on _both_ ends of this interaction.

**Comment by raldred** [comment] 2015-10-05 19:52
@tjschuck thanks for the lecture I'm fully aware of the concepts and guarantees offered by open source software, I've spent a lot of my own time building and contributing to projects. You've obviously misinterpreted my "sorry state" comment which was direct at Compass not Chosen.

I'm actually a paying customer of harvest so appreciate how useful you and your teams tools are for devs.

I intended to patch chosen-rails to build css out instead of just blindly including the scss source from Chosen, maximising its compatibility with the rails asset pipeline and removing any possibility of conflict.

**Comment by tjschuck** [comment] 2015-10-05 20:04
@raldred Sorry if I misunderstood you -- my apologies.  And thanks for understanding.

If you know what the problem is and could patch chosen-rails, that would be :+1: :+1:, because a lot of people seemingly have issues with it.

As for your comments about the maintenance of Compass, do you have any information you can share about this?  In the original issue body, it was mentioned that Compass wasn't well-maintained, and I asked:

> Also, Compass is no longer well-maintained? Do you have any reference to it being abandoned by its maintainers to back that up?

If it's _actually_ being abandoned, then we would certainly consider removing it as a dependency, since that's a pretty big liability for Chosen as well.  I couldn't find anything notable, though, and the original reporter never provided any additional information about that particular point -- if you can and can share it, that'd be appreciated.

I see that https://github.com/Compass/compass hasn't had a commit to `stable` since January, but that could be attributed to "stability" just as well as "abandoned".

**Comment by raldred** [comment] 2015-10-05 21:05
@tjschuck No problem at all, I'll sort chosen-rails.

I saw that, like you said there's nothing official to suggest it's abandoned, it was just feeling I got after talking to other devs on my team and at local meetups amongst the ruby community, although I accept this is just hearsay.
