### ISSUE TITLE
Chosen for disabling select observes events

### ISSUE THREAD

**Issue by Qwertovsky** [harvesthq/chosen#2460] opened 2015-10-15 15:01 UTC
1. Open in Chrome Browser (http://codepen.io/Qwertovsky/full/pjWOpp/)
2. Right mouse click on chosen
3. Left mouse click on chosen
4. Press [Ctrl+V]
5. Chosen dropdown appears.

**Comment by tjschuck** [comment] 2015-10-15 15:44
I cannot reproduce.

What Chrome version, OS, and OS version are you using?

Closing until more info is provided, then we'll reopen.

**Comment by Qwertovsky** [comment] 2015-10-16 06:38
Windows 7  6.1.7601 x64
Chrome 45.0.2454.101 m
Chrome 46.0.2490.71 m

**Comment by tjschuck** [comment] 2015-10-16 14:52
Okay -- I don't have access to a Windows computer, but I'm reopening based on your report.

**Comment by koenpunt** [comment] 2016-10-14 22:22
Just confirmed this is happening

**Closed** 2016-10-16 10:09 UTC
Labels: Bug, Has Solution, Windows
