### ISSUE TITLE
Feature/pull-request proposal: modify option/hooks

### ISSUE THREAD

**Issue by wejrowski** [harvesthq/chosen#2115] opened 2014-10-15 23:34 UTC
I created a couple hook options to allow you to modify chosen elements as they're created. I wanted to propose it before creating a pull request to see what you guys thought. 

The idea is you can pass associations in through option data values and/or do modifications to add images or colors or whatever, doing simple changes, or completely overriding the list elements. The actual Chosen code changes are super simple (see the commit here: https://github.com/wejrowski/chosen-rails/commit/d268664c72dc2b72f4aa7fb7c0afc5b0b3e98db7 -- I'm modifying it on the chosen-rails gem so we can use it in our app).

I'm using it on my team to add some color swatches to select options like this (but again you could add images or do anything else):

![Example](http://i.imgur.com/bEo1NBf.png)

And here would be a basic implementation. 

```javascript
$('.chosen-groups').chosen({
  // First hook to edit the selected options
  // both hooks give you the two basic things you need to alter it: the LI element chosen created,
  // which you can alter or override, and then the option variable that has all the data.
  edit_choice: function(element, option) {
    if (option.dataset.color) {
      element.addClass('search-choice-with-color');
      element.css('border-color', option.dataset.color);
    }
    return element;
  },

  // Second hook to edit the actual dropdown items
  edit_result: function(element, option) {
    if (option.dataset.color) {
      var swatch = '<span class="chosen-color-swatch" style="background: ' + option.dataset.color + ';"></span>';
      element.innerHTML = swatch + option.search_text;
    }
    return element;
  }
});
```

And the html (this also has a couple simple css styles I'm not showing here):

```html
<select class="chosen-groups" data-placeholder="Choose a tag" id="page_tag" multiple="multiple" name="page_tag">
  <option data-color="#f5b31a" value="1">Yellow</option>
  <option data-color="#2b5384" value="2">Blue</option>
  <option data-color="#fff" value="3">White </option>
  <option data-color="#ff4c47" value="4">Red</option>
  <option data-color="#420068" value="5">Etc</option>
  <option data-color="#333" value="6">Misc</option>
</select>
```

Let me know what you guys think.

**Comment by koenpunt** [comment] 2016-10-01 17:48
Essentially a duplicate of #692

**Closed by koenpunt** 2016-10-01 17:48 UTC
