### ISSUE TITLE
&amp; on select in label

### ISSUE THREAD

**Issue by sagarkt** [harvesthq/chosen#2600] opened 2016-05-10 10:02 UTC
In latest update, in chosen.jquery.js, on line 61, escapeExpression is used to get replace reserved character with character entities. But these entities are not converted back to it's connected reserved character.
So in list,
A & A
B
and if I select A & A in list, then it comes as A &amp; A.

If on line, 61 & 62, I remove call to escapeExpression() and directly use option.value then it's working fine. 

P.S. Sorry for bad English and if I did something wrong.

**Comment by DomHudson** [comment] 2016-05-12 13:27
Is this what you're referring to?

![image](https://cloud.githubusercontent.com/assets/10864294/15216086/91c02770-184d-11e6-9101-13a573b4c52b.png)

**Comment by sagarkt** [comment] 2016-05-12 13:39
Yes, only what you are seeing in list, I am getting it on selection.

**Comment by ketan-ghumatkar** [comment] 2016-05-18 12:50
Some one really need to see above issue

**Comment by koenpunt** [comment] 2016-10-01 17:10
Which version of Chosen are we talking about? And on what OS and in which browser? I can't reproduce this on macOS Chrome and Firefox.

**Comment by sagarkt** [comment] 2016-10-02 08:25
Chosen Version: v1.3.0
Ubuntu 14.04
Chrome 52.x

Also on Windows 7, 8.1, 10 and Firefox and IE 8.0+ and same chosen version

**Comment by DomHudson** [comment] 2016-10-03 08:13
For me it only happens if part of the html character matches another string from the option. 
For example if the option is  "a = 61" and you search for "61" the 61 text will be matched correctly but as the html encoded equals sign is "&#61;" the 61 in there will be underlined.

**Comment by koenpunt** [comment] 2016-10-03 09:03
Duplicate of #2548

**Closed by koenpunt** 2016-10-03 09:03 UTC
