### ISSUE TITLE
Feature request: add checkboxes to the list or allow selection of multiple items before the dropdown is closed.

### ISSUE THREAD

**Issue by zlatevbg** [harvesthq/chosen#2482] opened 2015-12-02 22:17 UTC
Hi,

If you can add checkboxes to the list it will be very easy to select several items faster by just clicking on the checkboxes before the dropdown is closed. Alternatively if possible you can force the dropdown to stay opened until you select multiple items from the list.

This will be especially useful if you don't know or are not sure about the items so you can't just type and search trough them.

Currently if I select an item from the list the dropdown is closed right away.
If I want to add another item I have to reopen it again, and again, and again....

**Comment by tjschuck** [comment] 2015-12-02 22:21
I don't think the checkboxes are a good UI for the feature, but the feature of "staying open" is a valid one.

However, it's a valid duplicate :)  Closing this as a duplicate of #1546 -- feel free to leave any feedback you have there. Thanks!

**Closed by tjschuck** 2015-12-02 22:21 UTC
