### ISSUE TITLE
spacebar scrolls on focused select with hidden search

### ISSUE THREAD

**Issue by kwliou** [harvesthq/chosen#1937] opened 2014-05-15 22:59 UTC
In v1.1.0 when select is focused (blue border), pressing the space bar opens it up like a native select (and doesn't scroll the page). However, when the select has search disabled (disable_search_threshold), pressing the space bar activates the select and also scrolls down the page.

**Comment by pfiller** [comment] 2016-06-04 18:55
Duplicate of #1834 which I just closed with this message:

> I think this is probably a #wontfix. disable_search_threshold has no search field so there's no easy way for us to capture keyboard events. We'd have to add a bunch of code around a feature I'd prefer didn't exist anyways (Chosen with no search field).

**Closed by pfiller** 2016-06-04 18:55 UTC
