### ISSUE TITLE
Select/Unselect all

### ISSUE THREAD

**Issue by medbenji** [harvesthq/chosen#2413] opened 2015-08-26 11:51 UTC
It would be a great feature to have the possibility of selecting / unselecting all at once when 'multiple' is activated.

Even with traditional select tags, we could CTRL+A them all to select everything.

**Comment by tjschuck** [comment] 2015-08-26 16:08
Duplicate of https://github.com/harvesthq/chosen/issues/1001 -- please leave any feedback you have there.  Thanks!

**Closed by tjschuck** 2015-08-26 16:08 UTC
