### ISSUE TITLE
Search doesn't work with parenthesis?

### ISSUE THREAD

**Issue by nhouse** [harvesthq/chosen#2297] opened 2015-03-31 16:51 UTC
If I have an option such as:

    Animals (dogs, cats, etc.)

And start typing in `dogs`, search doesn't show any results because of the opening parenthesis. In order to show a search result, I have to include the opening parenthesis (i.e. typing `(d` shows the option).

Is there a way to make the search function ignore parenthesis?

**Comment by tjschuck** [comment] 2015-03-31 18:09
Duplicate of https://github.com/harvesthq/chosen/pull/1483 -- please leave any additional feedback you have there.  Thanks!

**Closed by tjschuck** 2015-03-31 18:09 UTC
