### ISSUE TITLE
Search for multiple words in wrong order

### ISSUE THREAD

**Issue by MuyBien** [harvesthq/chosen#2265] opened 2015-03-11 09:06 UTC
Hi !
I wanted to search for multiple words but not in the good order. Means when I type foo bar, I want the results : 
- foo bar
- bar foo
- bar toto foo...

I saw the issue https://github.com/harvesthq/chosen/issues/677 and I saw the option search_contains that might be added after the solution proposed in the issue677. But this option allows to search in the same order (in my example only the first result will be showed). 

Am I missing something ?

**Comment by koenpunt** [comment] 2015-03-11 10:52
Duplicate of many ( #1438 #677 #2127 etc..), but you're talking about fuzzy search, which is being discussed over here: #858 and here: #2028

**Closed by koenpunt** 2015-03-11 10:52 UTC

**Comment by MuyBien** [comment] 2015-03-11 11:35
Oh OK ! Thanks I didn't know this word "fuzzy" ^^
So there is a patch but it's not in a final version for the moment.
Thanks I will take a look to the patch.
