### ISSUE TITLE
Empty CSS-File in chosen-npm Package

### ISSUE THREAD

**Issue by tojak** [harvesthq/chosen#2484] opened 2015-12-03 08:03 UTC
The chosen.css-File in the Node-Package "chosen-npm" only contains some comments, but no css!

**Comment by Shaazaam** [comment] 2015-12-18 18:08
I have noticed this issue as well...it'd be nice to be able to manage this correctly with node.

**Comment by lucjan** [comment] 2016-01-20 06:34
+1

**Comment by mmehlhope** [comment] 2016-01-30 02:02
+1

**Comment by ericrowan** [comment] 2016-02-29 20:52
I really don't understand this. Can someone explain what the issue is here?

**Comment by tjschuck** [comment] 2016-02-29 20:55
[chosen-npm](https://www.npmjs.com/package/chosen-npm) was not created by anyone on the Chosen team.  You'll have to try to contact the publisher directly and have them update the package to the latest version.

Closing this since it's outside the scope of Chosen itself (until we potentially take over NPM publishing — see #2550).

**Closed by tjschuck** 2016-02-29 20:55 UTC
