### ISSUE TITLE
width from style not being set due to explicity 0px width being set.

### ISSUE THREAD

**Issue by jadrake75** [harvesthq/chosen#1437] opened 2013-08-01 21:24 UTC
I have an angular app, in which the dialog is displaying and the selections are only shown when ready.  Chosen therefore assigns a 0px width, either though I included the 

inherit_select_classes: true

in the options.  One of those classes defines the width.  In this case the width is not necessary to be set since the inherited class has it.  One way to address this could be to have a configuration property in the order of 

no_explicit_width: true/false 

with the default being false.  This would imply a width: XXXpx is set as a element parameter and if the client is setting the width through a style it would not override it (since styles on the element will override class styles unless you use the dreaded !important)

Adding complexity in my case is the widths of the selections vary depending on what it is for.  Some like country, albums, collection etc. are wider whereas some like condition/grade are purposely shorter.  My temporarily workaround is I need to pass a directive attribute parameter to set the options.width when declaring my select as a chosen component (but this means I am declaring a width in HTML vs. CSS - thus breaking my general rule of HTML-5 purity)

Another workaround I may add in my Angular directive is to look for display/visibility change of the select and based on that derive the width for the chosen div.

I am using chosen over ui-select2 because of its excellent features and performance I have seen.  I realize why it is 0px, but it seems odd that this is being applied to the element div directly vs. other means (ie. css - which could then be overloaded)

**Comment by pfiller** [comment] 2016-06-02 22:26
Going to close this really old(!) issue. I think it's essentially a duplicate of #92 which would be fixed by #2495... right?

**Closed by pfiller** 2016-06-02 22:26 UTC
