### ISSUE TITLE
Problem in displaying multiple select list after initial selection - iPad

### ISSUE THREAD

**Issue by ysorin** [harvesthq/chosen#2612] opened 2016-05-27 18:45 UTC
To reproduce, go to demo page (Multiple Select) using iPad (I was in Safari). Appears the demo page uses jQuery version.
### Steps to reproduce
  1. Tap in the Multiple Select Chosen dropdown and Pick a Country from the list.

  2. Tap again to attempt to select another country.

Subsequent attempts to select from the list, without filtering, fail. The list should display when the user taps the input box on all selections, not just the first one, without having to filter.

I noticed the AbstractChosen.browser_is_supported function tests for other devices, including iPhone and iPod but not iPad. Is chosen supposed to be be enabled for iPad?

**Comment by pfiller** [comment] 2016-06-07 04:13
Duplicate of #2289

**Closed by pfiller** 2016-06-07 04:13 UTC
