### ISSUE TITLE
Feature Request: user entered option value

### ISSUE THREAD

**Issue by lucasmoeskops** [harvesthq/chosen#2533] opened 2016-02-11 11:46 UTC
It would be nice if there was an option to let the user enter a custom value in a chosen box. For example, a list could contain [Option 1], [Option 2], [Else...], with the last option opening an input field to enter a custom option. The value could then be added as `<option value="X">X</option>` to the select field where X is the user entered value, and be selected.

**Comment by koenpunt** [comment] 2016-02-14 23:19
Duplicate of many issues, and a proposed solution can be found here: #166

**Closed by koenpunt** 2016-02-14 23:19 UTC
