### ISSUE TITLE
Chosen does not work in a hidden div, display: none

### ISSUE THREAD

**Issue by alexandr2006** [harvesthq/chosen#2916] opened 2017-11-03 12:33 UTC
Chosen does not work in a hidden div, display: none

Source code: https://jsbin.com/pimoja/edit?html,css,output

**Comment by tjschuck** [comment] 2017-11-13 23:04
Pretty sure this is a duplicate of the long-standing https://github.com/harvesthq/chosen/issues/92.  Please feel free to leave any additional feedback you have there.  There's also a number of workarounds offered up on that issue.

**Closed by tjschuck** 2017-11-13 23:04 UTC
