### ISSUE TITLE
Add tagging support like Select2

### ISSUE THREAD

**Issue by chrispcb** [harvesthq/chosen#2606] opened 2016-05-19 13:39 UTC
Tagging support with Automatic tokenization like "Select2"  would be a nice feature.

**Comment by pfiller** [comment] 2016-06-02 21:25
Duplicate of #5. You may want to have a look at #166 which has a working solution.

**Closed by pfiller** 2016-06-02 21:25 UTC

**Comment by chrispcb** [comment] 2016-06-03 08:58
Nice, thank you.
You should add an exemple in demo page, no ?

**Comment by pfiller** [comment] 2016-06-03 18:46
> You should add an exemple in demo page, no ?

No, we don't document features in forks at this time. We only document the features that Chosen supports.

**Comment by iszlailorand** [comment] 2016-09-09 15:25
Can i ask u why don't you integrate this feature, it's nice one and a needed one?
