### ISSUE TITLE
remove compass as dependancy.

### ISSUE THREAD

**Issue by raldred** [harvesthq/chosen#2437] opened 2015-10-02 21:44 UTC
Is it possible to remove compass as a dependancy, it has tons of issues with recent rails versions and you're only using it for a couple of mixins which have collisions with the superior [bourbon](http://bourbon.io/) mixins

**Comment by koenpunt** [comment] 2015-10-03 16:14
Duplicate of #2368

**Closed by koenpunt** 2015-10-03 16:14 UTC
