### ISSUE TITLE
Select options when click on optiongroup - Feature Request

### ISSUE THREAD

**Issue by minikiz** [harvesthq/chosen#2773] opened 2017-02-14 15:52 UTC
For selectboxes with the “multiple” attribute, and the “options” organized in “optiongroups”, it would be great to add the following feature: if an user clicks on an optiongroup name, select/unselect all its options. 
It could be very useful in order to allow a fast input of multiple values. Moreover, it could be an optional feature, configurable via the plugin options.

Thanks, and congrats for your work. The plugin is awesome!

**Comment by jamesalbert** [comment] 2017-02-14 16:28
Is this more or less what you're talking about? #2678

**Comment by tjschuck** [comment] 2017-02-14 17:14
Seems like it.  That PR also links to #323 as the original issue of this, so I'm going to close this as a duplicate of that.  Please leave any feedback you have on #323 — thanks!

**Closed by tjschuck** 2017-02-14 17:14 UTC
Labels: Feature Request
