### ISSUE TITLE
chosen dropdown gets slowdown.

### ISSUE THREAD

**Issue by nandhacse** [harvesthq/chosen#2392] opened 2015-08-06 14:12 UTC
i have an array with just 200 records which is obtained from the database. And when i try to load all the datas into dropdown .. i takes nearly 10-15 seconds to be loaded fully. need your guidence

**Comment by tjschuck** [comment] 2015-08-07 18:16
200 records should not be slow.

What browser, browser version, OS, and OS version are you using?  And what version of Chosen?  If not the latest version, does it still happen on the [latest version](https://github.com/harvesthq/chosen/releases)?

Additionally, please link to a publicly accessible page (or a [Fiddle](http://jsfiddle.net)) that shows the issue so we can attempt to reproduce.

Closing until more info is provided, then we'll reopen.

**Closed by tjschuck** 2015-08-07 18:16 UTC

**Comment by nandhacse** [comment] 2015-08-11 04:30
Hi,

I am using google chrome Version 42.0.2311.90 (64-bit), ubuntu OS(14.04
lts) and chosen version is v0.13.0

*Regards,*

*Mr. M.Nandhakumar*

*nandhacse2010@gmail.com <nandhacse2010@gmail.com>*

*+91-9597380274*

**Comment by nandhacse** [comment] 2015-08-11 04:38
In my project chosen hasn't working for ng-options. So that i go for another solution which i have added below.


          Customer.getBoardNames(function (boards) {
                    $scope.boardmaster=boards;
                    $scope.boards="";
                    $scope.boards="<option class='category'></option>";
                    boards.forEach(function(singleboard){
                        singleboard.boards.forEach(function(board){
                          $scope.optionboards='';
                            $scope.optionboards="<option class='category'>"+board.boardNames+"</option>";
                            $scope.boards=$scope.boards.concat($scope.optionboards);
                        })
                        $('#boards').html(
                            $compile(
                                $scope.boards
                            )($scope)
                        ).chosen({width: "96%"});
                        $('#boards').trigger("liszt:updated");
                    });
                })

**Comment by tjschuck** [comment] 2015-08-11 16:12
Version 0.13.0 of Chosen is more than 2 years old.  There have been significant performance improvements made since then.  You should absolutely try [the most current version](https://github.com/harvesthq/chosen/releases).
