### ISSUE TITLE
Don't close on multiple select

### ISSUE THREAD

**Issue by thekrotek** [harvesthq/chosen#2292] opened 2015-03-29 22:28 UTC
Is it possible to add an option to NOT close the dropdown menu every single click on the option, when selecting multiple options? It's pretty annoying, when you need to select like 10 options and for that have to reopen dropdown each time.

Would be much better, if you could select as much options as you need and then just click anywhere outside dropdown menu to close it.

**Comment by subakva** [comment] 2015-03-30 02:45
There's a discussion of this issue and some hacks here: #1546

**Comment by thekrotek** [comment] 2015-03-30 07:14
Thank you for the tip. I tried the hack and it works, indeed. Too bad it's not implemented in the main code yet.

**Comment by tjschuck** [comment] 2015-03-31 16:36
Closing this as a duplicate of #1546 -- feel free to leave any feedback you have there.  Thanks!

**Closed by tjschuck** 2015-03-31 16:36 UTC
