### ISSUE TITLE
Feature Request: Dynamically Add Values + possible fix

### ISSUE THREAD

**Issue by lordspace** [harvesthq/chosen#2202] opened 2015-01-20 18:27 UTC
Hi,

It would be really nice if when there are no results found to allow the value to be added to the select.
This would simplify the UI for example if the user has to choose Projects they can type the name and if no matches are shown then show "Create Project Name". Then in the backend if the selected value is 0 then add the new project.

this person [ https://boundlessjourney.wordpress.com/2014/06/12/adding-new-values-to-chosen-plugin/ ] has attempted to do something like this but I he fixed the code. I noticed that I can hook into 'chosen:no_results' even to add the values dynamically not sure if that's the best way to add it.

```
$('.ez_select_editable').on('chosen:no_results', function (json) {
	var id = 123;
	var value = 'Yahoo';
	
	$(json.currentTarget).append($('<option></option>')
        .val(id)
        .attr('selected', 'selected')
        .html(value)).trigger("chosen:updated");
		
	return true;
});
`

**Comment by tjschuck** [comment] 2015-01-20 20:03
Duplicate of #166 -- please leave any feedback you have there.

**Closed by tjschuck** 2015-01-20 20:03 UTC
