### ISSUE TITLE
Select opens when click on area below it in IE

### ISSUE THREAD

**Issue by gtrubach** [harvesthq/chosen#2892] opened 2017-09-30 13:11 UTC
In IE select become opened when somebody click below it in scrollbar area after opening and closing select. Reproduced on https://harvesthq.github.io/chosen/.

### Steps to reproduce

  1. Click on select to toggle dropdown.

  2. Click outside the select item to close dropdown.

  3. Click below select near the scrollbar area.

Demo:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/10942688/31046017-d12a9482-a5f9-11e7-8b6d-46d56b4ceef5.gif)

### Expected behavior

Select's dropdown should not be toggled.

### Actual behavior

Select's dropdown become toggled.

### Environment

  - **Chosen Version**: 1.8.2

  - **jQuery or Prototype Version**: version on https://harvesthq.github.io/chosen/

  - **Browser and Version**: IE 11.608.15063.0

  - **OS and Version**: Windows 10

**Comment by tjschuck** [comment] 2017-10-02 18:47
Duplicate of https://github.com/harvesthq/chosen/pull/2886 — closing this in favor of that.  Please feel free to leave any additional feedback you have there!

**Closed by tjschuck** 2017-10-02 18:47 UTC
