### ISSUE TITLE
cant't clone attributes to chosen-select options ?

### ISSUE THREAD

**Issue by ridwanskaterock** [harvesthq/chosen#2730] opened 2016-10-18 07:28 UTC
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.6.2/chosen.css">
i have a single select as

     <select data-placeholder="Choose a Country..." class="chosen-select county" >
            <option value=""></option>
            <option data-area="europa" data-id="001"  value="United States">United States</option>
            <option data-area="europa" data-id="002"  value="United Kingdom">United Kingdom</option>
            <option data-area="asian" data-id="003"  value="Afghanistan">Indonesia</option>
            <option data-area="asian" data-id="004"  value="Afghanistan">Malaysia</option>
      </select>

i have attributes in options will be generate,
if i change the country, why attribute data-area is undefined,
why element has been generate dropdown ul li can't clone attribute from select element ?

so the result like this

     <div class="chosen-container chosen-container-single" style="width: 116px;" title="">
     <a class="chosen-single">
      <span>Indonesia</span>
      <div><b></b></div>
     </a>
     <div class="chosen-drop">
         <div class="chosen-search"><input autocomplete="off" type="text">     </div>
           <ul class="chosen-results">
             <li class="active-result" style="" data-option-array-index="1">United States</li>
             <li class="active-result" style="" data-option-array-index="2">United Kingdom</li>
             <li class="active-result result-selected" style="" data-option-array-index="3">Indonesia</li>
             <li class="active-result" style="" data-option-array-index="4">Malaysia</li>
          </ul>
       </div>
    </div>

why not like this (attributes clone in element ul li)

    <div class="chosen-container chosen-container-single" style="width: 116px;" title="">
       <a class="chosen-single">
          <span>Indonesia</span>
          <div><b></b></div>
       </a>
       <div class="chosen-drop">
          <div class="chosen-search"><input autocomplete="off" type="text">    </div>
          <ul class="chosen-results">
             <li data-area="europa" data-id="001" class="active-result" style="" data-option-array-index="1">United States</li>
             <li data-area="europa" data-id="002" class="active-result" style="" data-option-array-index="2">United Kingdom</li>
             <li data-area="asian" data-id="003" class="active-result result-selected" style="" data-option-array-index="3">Indonesia</li>
             <li data-area="asian" data-id="004" class="active-result" style="" data-option-array-index="4">Malaysia</li>
          </ul>
       </div>
    </div>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js" type="text/javascript"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.6.2/chosen.jquery.js" type="text/javascript"></script>
    <script type="text/javascript">
      var config = {
        '.chosen-select'           : {},
        '.chosen-select-deselect'  : {allow_single_deselect:true},
        '.chosen-select-no-single' : {disable_search_threshold:10},
        '.chosen-select-no-results': {no_results_text:'Oops, nothing found!'},
        '.chosen-select-width'     : {width:"95%"}
      }
      for (var selector in config) {
        $(selector).chosen(config[selector]);
      }

      $('.county').on('change', function() {
  	    alert('id : ' + $(this).attr('data-area'));
      });
    </script>

**Comment by koenpunt** [comment] 2016-10-19 12:34
Duplicate of #2591 with proposed solution in #2574

**Closed by koenpunt** 2016-10-19 12:34 UTC
