### ISSUE TITLE
Scrolling = sharp jerking

### ISSUE THREAD

**Issue by Demyan112rv** [harvesthq/chosen#2543] opened 2016-02-20 14:45 UTC
At first, I found same issue #1818, but this issue very old. And i think, open new - good solution.

When i scroll opened select with options i have sharp jerking and scroll to the end list options.

Used on page:
jQuery v2.2.0
Chosen 1.5.1
jQuery Mousewheel 3.1.13

Testing in Chrome 48 and Safari 9 on MacOS

**Comment by Demyan112rv** [comment] 2016-02-20 14:48
It may be connected with event 'mousewheel.chosen DOMMouseScroll.chosen'

**Comment by tjschuck** [comment] 2016-02-22 19:52
@Demyan112rv Does it happen for you on [the Chosen homepage](http://harvesthq.github.io/chosen/)?  I cannot reproduce any scrolling performance issues there.

If not, please link to a publicly accessible page (or a [Fiddle](http://jsfiddle.net)) that shows the issue so we can attempt to reproduce.

Closing for now, but will reopen when more information is provided.  Thanks!

**Closed by tjschuck** 2016-02-22 19:52 UTC

**Comment by iKonrad** [comment] 2016-02-23 08:02
I have the very same thing! It's extremely annoying. 
It looks like the uncommenting these two lines seems to fix the issue:

```
    Chosen.prototype.result_do_highlight = function(el) {
      var high_bottom, high_top, maxHeight, visible_bottom, visible_top;
      if (el.length) {
        this.result_clear_highlight();
        this.result_highlight = el;
        this.result_highlight.addClass("highlighted");
        maxHeight = parseInt(this.search_results.css("maxHeight"), 10);
        visible_top = this.search_results.scrollTop();
        visible_bottom = maxHeight + visible_top;
        high_top = this.result_highlight.position().top + this.search_results.scrollTop();
        high_bottom = high_top + this.result_highlight.outerHeight();
        if (high_bottom >= visible_bottom) {
          // return this.search_results.scrollTop((high_bottom - maxHeight) > 0 ? high_bottom - maxHeight : 0);
        } else if (high_top < visible_top) {
          // return this.search_results.scrollTop(high_top);
        }
      }
    };
```

But I'd rather wait for a more permanent solution

**Comment by tjschuck** [comment] 2016-02-23 16:03
@iKonrad Does it happen for you on [the Chosen homepage](http://harvesthq.github.io/chosen/)?

If not, can you link to a publicly accessible page (or a [Fiddle](http://jsfiddle.net)) that shows the issue?

**Comment by Demyan112rv** [comment] 2016-02-27 08:27
@tjschuck @iKonrad working good for me in all browsers when i commenting this line:
`return this.search_results.scrollTop((high_bottom - maxHeight) > 0 ? high_bottom - maxHeight : 0);`
I tried found solution for this bug, but i not understand where problem. 

A problem somewhere in variable **high_top**, because i get **high_bottom** always more than **visible_bottom**

**Comment by rs-orlov** [comment] 2016-02-29 04:17
@tjschuck @iKonrad @Demyan112rv just update to jQuery 2.2.1. There was a bug with $el.position() in 2.2.0 version. http://blog.jquery.com/2016/02/22/jquery-1-12-1-and-2-2-1-released/

**Comment by tjschuck** [comment] 2016-02-29 20:16
Ah, yes, jQuery 2.2.0 was causing another scroll-based issue as well: #2506

Keeping this closed as its a jQuery issue (for which a fix has been issued) and not caused by Chosen at all.

Thanks everyone!

**Comment by Demyan112rv** [comment] 2016-03-02 09:03
@rs-orlov Thank You! It's working after update jQuery!

**Comment by iKonrad** [comment] 2016-03-02 09:46
Thanks for the update!
