### ISSUE TITLE
container_width = 0px

### ISSUE THREAD

**Issue by tavoarcila** [harvesthq/chosen#2795] opened 2017-03-15 17:18 UTC
Hi, I'm using a very old template (janux) for a system I've. that template used 0.98 version of chosen, and the .trigger("chosen:updated") did not work,

I tried updating to latest version but it only show a very tiny button, so, after some research and debug I found out that AbstractChosen.prototype.container_width was returning 0px (zero) 

To fix in my hurry to get it fixed I just did the following:
AbstractChosen.prototype.container_width = function() {
      toReturn = "";
      if (this.options.width != null) {
        toReturn =  this.options.width;
      } else {
        toReturn = "" + this.form_field.offsetWidth + "px";
      }
      if (toReturn=="" || toReturn=="0px")
      	toReturn = "150px";
      return toReturn;
    };

This fixed the tiny button problem displaying the select correctly and with the latest version .trigger("chosen:updated")  work like a charm.

I hope you can find a most professional solution for the container_width issue. Thank you

NOTE: The chosen select I'm using is inside a modal window, maybe this helps,

Thank you in advance for your help

Gustavo Arcila

**Comment by walter-gonzalez** [comment] 2017-07-04 19:24
I have a similar issue with the container width being set to width=0px; in the style attribute.

**Comment by mr-KVA** [comment] 2017-07-31 15:30
Hi, have similar issue:

Seems this issue is appears when chosen initialized before parent container is hidden.
I made simple code to reproduce the issue : https://jsfiddle.net/vdrs92rp/6/

Also according to (Mozilla https://developer.mozilla.org/docs/Web/API/HTMLElement/offsetWidth) this property is not working properly also with "position : fixed".

I see few workarounds:

1. use hardcoded width in chosen js

2. setting width of chosen js by js script after Chosen is inited (to override 0px)
(for this we don't need to modify any code in chosen lib)

3. use other methods to get width of select (jQuery width?) or at least use this method as failback when offsetWidth returned 0/null

**Comment by tjschuck** [comment] 2017-11-13 23:05
Pretty sure this is a duplicate of the long-standing https://github.com/harvesthq/chosen/issues/92.  Please feel free to leave any additional feedback you have there.  There's also a number of workarounds offered up on that issue.

**Closed by tjschuck** 2017-11-13 23:05 UTC
