### ISSUE TITLE
Chosen set width 0 in non visible selects

### ISSUE THREAD

**Issue by casph** [harvesthq/chosen#2371] opened 2015-07-16 12:41 UTC
solution proposal:

    AbstractChosen.prototype.container_width = function() {
      if (!this.form_field_jq.is(":visible")) {
        var dummy = this.form_field_jq.clone();
        dummy
          .css({
            "left" : "-9999px",
            "right" : "auto",
            "position" : "absolute",
            "display" : "block",
            "visibility" : "visible"
          })
          .appendTo(document.body);
        var width = dummy.innerWidth();
        dummy.remove();
        return width + "px";
      }
      if (this.options.width != null) {
        return this.options.width;
      } else {
        return "" + this.form_field.offsetWidth + "px";
      }
    };

**Comment by kevin-brown** [comment] 2015-07-16 13:56
This sounds like a duplicate of https://github.com/harvesthq/chosen/issues/795.

**Comment by pfiller** [comment] 2016-06-02 22:27
Or a duplicate of #92. Closing!

**Closed by pfiller** 2016-06-02 22:27 UTC

**Comment by KZeni** [comment] 2017-06-01 19:29
I just leave the default chosen width option (auto) and add
```
.chosen-container { min-width:5em; }
```
to my site's CSS (adjusting the min-width as needed). This makes it never become 0px (or just too small to use) while still fitting the select's ideal width when possible (forcing a 100% width or something to that effect doesn't work well when you have select elements inline with other content & this method addresses the core issue as well as allowing for inline select elements & seemingly offering the simplest & most straightforward implementation).
