### ISSUE TITLE
Chosen search does not work for options with (text)

### ISSUE THREAD

**Issue by oniofchaos** [harvesthq/chosen#2384] opened 2015-08-05 00:31 UTC
Given the following html:
```html
<select chosen>
  <option value="1">test</option>
  <option value="2">rawr (this cats meow) is fun</option>
</select>
```

Searching for "this" will return no results, but searching for "(this", "cats", or "meow" returns the second option. I should be able to search for "this" as well.

This is happening on Chosen 1.4.2 on my Mac on the latest Chrome/Safari.

**Comment by tjschuck** [comment] 2015-08-05 13:23
This is a known issue -- duplicate of https://github.com/harvesthq/chosen/pull/1483.  Please leave any feedback you have there.  Thanks!

**Closed by tjschuck** 2015-08-05 13:23 UTC
