### ISSUE TITLE
List of options gets scrolled completely down on hover and on scroll

### ISSUE THREAD

**Issue by Senthe** [harvesthq/chosen#2504] opened 2016-01-14 13:31 UTC
On the slightest scroll and on hover the list of items gets scrolled completely down and it's impossible to scroll it up. It is however possible to scroll entirely up using the scrollbar. Using the scrollbar I can scroll to any part of the list but on hover it gets scrolled down. Recording:
https://www.youtube.com/watch?v=6BXnnUVmMqo

**Comment by tjschuck** [comment] 2016-01-14 15:53
What browser, browser version, OS, and OS version are you using?  And what version of Chosen?  If not the latest version, does it still happen on the [latest version](https://github.com/harvesthq/chosen/releases)?

Additionally, please link to a publicly accessible page (or a [Fiddle](http://jsfiddle.net)) that shows the issue so we can attempt to reproduce.  Alternatively, confirm that the [Chosen demo page](http://harvesthq.github.io/chosen/) shows the issue.

Closing until more info is provided, but then we'll reopen.

**Comment by JoannaFalkowska** [comment] 2016-01-15 10:21
Sorry for not very specific description.

I use gem rails-assets-chosen (1.4.2) from https://rails-assets.org/ which should indeed deliver version 1.4.2. I used the newest desktop Chrome 47.0.2526.106, OS X El Capitan.

I can't really provide public page since it's my work project still in development. I did setup a jsfiddle, but it's not replicating the problem. https://jsfiddle.net/w2a6k729/ 

I'm kind of clueless what may be causing it.

**Comment by tazmanska** [comment] 2016-01-15 12:55
You can reproduce the problem by using jQuery 1.12.0 https://jsfiddle.net/hzzmrw9p/4/

**Comment by JoannaFalkowska** [comment] 2016-01-15 13:16
I have jquery-rails (4.1.0) and jquery-ui-rails (5.0.5). Not sure which version of jQuery they provide. Which version of jQuery should be stable used with Chosen?

**Comment by tazmanska** [comment] 2016-01-15 13:27
@JoannaFalkowska jQuery 1.11.1 seems to work just fine, 1.12.0 is the problem.

**Comment by Senthe** [comment] 2016-01-15 13:34
Okay, I'll try downgrading to this one!

**Comment by tazmanska** [comment] 2016-01-15 16:07
@Senthe You should reopen this issue.

**Comment by tjschuck** [comment] 2016-01-15 23:20
@Senthe @tazmanska Thanks!  I can confirm that this fiddle shows the issue (Safari 9.0.2, OS X 10.11.2): https://jsfiddle.net/hzzmrw9p/4/

Reopening!

**Comment by CSI68** [comment] 2016-01-22 08:16
Hi,

The problem went with jQuery 1.12.x, it is the same issue than https://github.com/harvesthq/chosen/issues/2506

A hack has been found and it working!

**Comment by DrowningElysium** [comment] 2016-03-10 10:13
I can confirm that upgrading to version 1.12.1 fixes the issue. 1.12.0 is the one with the issue.

**Closed** 2016-03-13 10:58 UTC
