### ISSUE TITLE
Feature Request: Allow float/custom values to be specified in search field and preserve that value

### ISSUE THREAD

**Issue by jiteshsojitra** [harvesthq/chosen#2848] opened 2017-07-11 07:42 UTC
Feature Request: Allow float/custom values to be specified in search field and preserve that value

I will search the text and chosen dropdown will select the value if exists but if value doesn't present then it gives special message. I would like to go ahead with value mentioned in the edit field for further processing.

Steps:
1. Search some word in chosen dropdown
2. When"No results match" shown, put focus outside - it clears value

Instead of clearing value, custom text should remain as it is so we can use it different purpose as a floating value used specified.

**Comment by Skeeve** [comment] 2017-10-01 20:14
Duplicate of #2895

**Comment by jiteshsojitra** [comment] 2017-10-01 20:25
Please close this bug, sorry i recall that i filed this issue on July 2 months ago. Seems like no progress/comment and probably that reason i filed that bug again by mistake :)

**Closed** 2017-10-02 18:29 UTC
