### ISSUE TITLE
Support for require JS

### ISSUE THREAD

**Issue by ecsinsi** [harvesthq/chosen#2342] opened 2015-06-10 19:07 UTC
I'm using this as part of a large project and have modified the JS to work with Require JS that uses a private jquery instance. Is this worth opening a pull request for? As far as I know, making jquery plugins AMD aware is backwards compatible.

**Comment by cralfaro** [comment] 2015-06-18 07:23
Hi, I am using too chosen with requireJS and usually running selenium, i got multiple failures when try to use chosen() function, do you know how to modify the current chosen (1.4.2) to make it AMD compatible? Do you know if a new version AMD compatible its in process? 

Thanks!

**Comment by ecsinsi** [comment] 2015-06-18 16:08
I've uploaded it here: http://www.filedropper.com/chosenjquery

**Comment by isochronous** [comment] 2015-07-09 15:59
@cralfaro, if you're using requireJS, you're going to need to learn how to do that yourself.  Luckily, there's a good resource that should help you here: https://github.com/umdjs/umd

**Comment by cralfaro** [comment] 2015-07-09 16:07
Hi Jeremy,

You are right, finally i had to migrate the chosen and others js 
libraries to AMD format.

Thanks for your link, was new for me and i am sure will be usefull :)

**Comment by pfiller** [comment] 2016-06-07 16:41
Duplicate of #2215, which is more thorough.

**Closed by pfiller** 2016-06-07 16:41 UTC
