### ISSUE TITLE
v1.7 does not work search Cyrillic text

### ISSUE THREAD

**Issue by webinteger** [harvesthq/chosen#2810] opened 2017-04-16 09:12 UTC
In the version v1.7 does not work search Cyrillic text,  but  in the version 1.6.2 search works good!!

**Comment by lockz** [comment] 2017-04-20 04:27
+1

**Comment by varyen** [comment] 2017-04-21 20:18
I can confirm this

**Comment by koenpunt** [comment] 2017-04-22 19:56
Duplicate of #2805

**Closed by koenpunt** 2017-04-22 19:56 UTC
