### ISSUE TITLE
Init 1000 drop down list take alot of time 

### ISSUE THREAD

**Issue by tabaolan1987** [harvesthq/chosen#3101] opened 2020-09-16 08:04 UTC
Summarize your issue here.

### Steps to reproduce

Tell us how to reproduce this issue.

  1. Using ajax to create 1000 select html with class chosen-select

  2. Append those selects at step 1 into the table.

### Expected behavior
Should not take more than 2 minutes.

### Actual behavior

It took more than 2 minutes to render the chosen drop down.

### Environment

  - **Chosen Version**: v1.8.7 

  - **jQuery or Prototype Version**: 1.9.1

  - **Browser and Version**: Chrome - Version 85.0.4183.102 (Official Build) (64-bit)

  - **OS and Version**: WINDOW 10

### Additional information

Any other information you want to share that is relevant to the issue being reported. This might include the lines of code that you have identified as causing the bug, or potential solutions and workarounds.

**Comment by pjfsilva** [comment] 2021-02-10 17:42
Please provide a codepen or jsfiddle code example of that problem. Chosen doesn't support ajax loading of options by default so it's not clear what you are doing. 

Your performance problem is most likely on the way you add/manage those options and not on chosen itself.

A very simple example with [> 3900 options](https://jsfiddle.net/bmj68ek0/2/) loads 'instant' on my machine (also very dependent on clients machine performance, of course).

**Comment by tjschuck** [comment] 2021-02-10 18:07
There is already a canonical issue for "performance issues with very large lists", but that's for lists in the 20,000+ range.  Closing this as either a dupe of that (https://github.com/harvesthq/chosen/issues/2580), or something else happening (@pjfsilva's AJAX-loading related comments).

**Closed by tjschuck** 2021-02-10 18:07 UTC
