### ISSUE TITLE
Chosen and hidden Overflow in Container

### ISSUE THREAD

**Issue by ckosmowski** [harvesthq/chosen#1479] opened 2013-08-16 06:41 UTC
I'm trying to use chosen in a complex web application which has a border layout with multiple individual regions which have `overflow` set to `hidden` to prevent the contents from scrolling.

Unfortunately this makes the chosen `chosen-drop` element beeing partially invisble. In my opinion the dropdown of chosen should be able to be displayed even if the overflow of the container is hidden (absolute positioning) because this is the way you would expect it to work since the selecboxes behave that way. Please see this jsfiddle:

http://jsfiddle.net/ZJ73j/1/

for a demonstration and comparison.

The selectmenu which is in development for jquery-ui is handling it the way i would expect it. (Unfortunately for now it screws up for many other features like refreshing its contents).

**Comment by koenpunt** [comment] 2016-09-16 10:49
Duplicate of #86

**Closed by koenpunt** 2016-09-16 10:49 UTC
