### ISSUE TITLE
Bug when search for phrase from middle words and contain blank space

### ISSUE THREAD

**Issue by jyuan** [harvesthq/chosen#2253] opened 2015-03-03 19:23 UTC
When I search for a phrase, for example 

> Brooklyn New York

It works fine when I type 

> Brooklyn New

and I can easily choose the item that I want.

But when I try to type 

> New Y

It doesn't work and return null.

**Comment by tjschuck** [comment] 2015-03-03 19:31
Duplicate of https://github.com/harvesthq/chosen/pull/1483 -- please leave any feedback you have there.  Thanks!

**Closed by tjschuck** 2015-03-03 19:31 UTC
