### ISSUE TITLE
If <option> paste only Russian text, it does not appear in the selection list.

### ISSUE THREAD

**Issue by Flayter** [harvesthq/chosen#2873] opened 2017-08-26 20:12 UTC
If <option> paste only Russian text, it does not appear in the selection list.

`
<select name="" class="chosen">
    <option value="1">текст любой</option>
    <option value="2">text2</option>
    <option value="3">text3</option>
  </select>
`
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.js" type="text/javascript"></script>
  <script src="chosen.jquery.js" type="text/javascript"></script>
    <script>
          $(".chosen").chosen({disable_search_threshold: 10});
    </script>
`

If add options search_contains: true, then worked.
`search_contains: true`

http://joxi.ru/Q2Kx57dt9yZgwA

### Environment

  - **Chosen Version 1.8.0**:

  - **jQuery  3.2.1**:

  - **Chrome 60.0.31 **:

  - **Windows 7**:

**Comment by chengang0621** [comment] 2017-08-27 02:57
when I use chinese ,It does not appear in the selection list

**Comment by evanre** [comment] 2017-08-28 10:01
Hi, I've update the plugin and got the same issue. Try to use 1.7 version.
I hoped, in 1.8  #2821 will be fixed, but instead got new problems )

**Comment by tjschuck** [comment] 2017-08-28 16:13
Pretty sure this is a duplicate of #2821 — closing this in favor of that one.  Please leave any additional feedback you have there. Thanks!

**Closed by tjschuck** 2017-08-28 16:13 UTC
