### ISSUE TITLE
Dropdown opens only to down

### ISSUE THREAD

**Issue by jterlouw951** [harvesthq/chosen#2337] opened 2015-06-04 18:49 UTC
Is there anyway that if there is no space under the select it should open above it?
Also I have issues to set the z-index proper even with z-index on 999

**Comment by tjschuck** [comment] 2015-06-04 18:53
Duplicate of https://github.com/harvesthq/chosen/issues/155.  Please leave any feedback you have there.

**Closed by tjschuck** 2015-06-04 18:53 UTC
