### ISSUE TITLE
Chosen single and multi select options close on pressing down key

### ISSUE THREAD

**Issue by coinjabber** [harvesthq/chosen#2249] opened 2015-02-27 03:53 UTC
I have two chosen dropdowns (both single) on my site where after I have entered some information and narrowed down choices it lets me skip through to my desired choice with the down arrow on my keyboard.

Then I have two other chosen dropdowns (one single, one multi) where the options list completely disappears after I press the down key. Is there any particular parameter or maybe something about positioning that determines this behavior?

**Comment by tjschuck** [comment] 2015-02-27 16:02
What browser, browser version, OS, and OS version are you using?  And what version of Chosen?

Additionally, please link to a publicly accessible page (or a [Fiddle](http://jsfiddle.net)) that shows the issue so we can attempt to reproduce.

Closing until more info is provided, then we'll reopen.

**Closed by tjschuck** 2015-02-27 16:02 UTC

**Comment by coinjabber** [comment] 2015-02-27 18:20
Is it ok if I show you the example in a non public page or does it have to be public? I could create an account for you.

**Comment by tjschuck** [comment] 2015-02-27 20:56
Public, please.  I am not necessarily the person that might investigate your issue.  A Fiddle is the best bet, because then you can reduce the issue to its essential components to reproduce.

**Comment by coinjabber** [comment] 2015-02-27 21:30
OK, let's try a public link first: I created one here now http://dev.coinjabber.com/test.html

The two dropdowns that behave in the manner I described on a Mac OS 10.7 in Chrome, Firefox, and Safari, not sure about IE.

**Comment by tjschuck** [comment] 2015-02-27 21:36
I'm not sure where or what your issue is on that page.  Please give a step-by-step reproduction, including what you see and what you _expected_ to see.

**Comment by coinjabber** [comment] 2015-02-27 21:45
Oops, sorry about that, I hit submit too soon. See steps in the edited comment now.
