### ISSUE TITLE
Filter with " (quotation mark)

### ISSUE THREAD

**Issue by Pilat66** [harvesthq/chosen#2165] opened 2014-12-12 11:19 UTC
If the original string contains a quotation mark, then the string is searched only with the quotation marks in the search terms.
Example:

    <option value="123"  >&quot;NameOfFirm&quot;</option>

Search by **NameOf** pattern does not found any string, search by **"NameOfFirm** found string.

**Comment by pfiller** [comment] 2016-06-07 03:45
A duplicate of #121 more or less. The `search_contains` option is a workaround.

**Closed by pfiller** 2016-06-07 03:45 UTC
