### ISSUE TITLE
Add multiline for options?

### ISSUE THREAD

**Issue by trungdq88** [harvesthq/chosen#2276] opened 2015-03-24 03:06 UTC
How about provide an option to add a description line at the bottom of each option?

	<select>
	    <option value="1" data-description="This car has 4 wheels">Toyota</option>
	    <option value="2" data-description="This car has 2 wheels">Honda</option>
	</select>

It will show up the dropdown box like this
![1](https://cloud.githubusercontent.com/assets/4214509/6795080/5fb06f7e-d20d-11e4-94cb-ea2d6fe2ffd1.jpg)

**Comment by tjschuck** [comment] 2015-03-24 18:25
Duplicate of https://github.com/harvesthq/chosen/pull/692 -- please leave any feedback you have there.  Thanks!

**Closed by tjschuck** 2015-03-24 18:25 UTC
