### ISSUE TITLE
Adding this.search_results.scrollTop() in Chosen.prototype.result_do_highlight breaks scrolling for long lists

### ISSUE THREAD

**Issue by rabinnh** [harvesthq/chosen#2578] opened 2016-03-23 14:36 UTC
Vertical scrolling on long lists is broken when moving mouse cursor from scrollbar to select.

### Steps to reproduce

1. Create a single select list with enough entries for at least 3 full "pages" based on the size of the dropdown.

2. Use the scrollbar to scroll down more than halfway through the list.

3. Move the cursor to select an item.

4. The list will jump to the end.

### Environment

Chosen 1.5.1

jQuery 2.2.0

Chrome LinuxVersion 49.0.2623.87 (64-bit)

Ubuntu 14.04.3

### Additional information

The bug is at this line:

**Comment by Pezmc** [comment] 2016-03-23 14:48
Duplicate of #2579

**Closed by Pezmc** 2016-03-23 14:48 UTC
