### ISSUE TITLE
How to open Chosen drop down outside  scroll modal, like HTML dropdown…  

### ISSUE THREAD

**Issue by uirajatmal** [harvesthq/chosen#2601] opened 2016-05-11 16:13 UTC
How to open Chosen drop down outside 
![scroll-modal](https://cloud.githubusercontent.com/assets/4692315/15188041/c70857f4-1771-11e6-91f8-5e3acf335095.png)
 scroll modal, like HTML dropdown…

**Comment by pfiller** [comment] 2016-06-02 21:25
Duplicate of #96. There are some solutions discussed in there, but there's currently no official solution.

**Closed by pfiller** 2016-06-02 21:25 UTC
