### ISSUE TITLE
chosen does not render correctly when it is indise jQuery toogleSlide

### ISSUE THREAD

**Issue by sukrub** [harvesthq/chosen#2581] opened 2016-03-28 19:22 UTC
Hi:

When I put chosen comboBox inside a div that opens/(extends) with jQuery slideToggle I get that little comboBox.
![image_1](https://cloud.githubusercontent.com/assets/18124572/14087511/2c75afde-f4df-11e5-9f27-9ee285d77a6a.jpg)
![image_2](https://cloud.githubusercontent.com/assets/18124572/14087512/2c790a1c-f4df-11e5-8a6a-84d4cf39d515.jpg)

But when I put the chosen comboBox in the reqular document everything works fine.
![image_3](https://cloud.githubusercontent.com/assets/18124572/14087517/330e12fa-f4df-11e5-9a04-5cf7cecf9394.jpg)

Any help would be greatly appreciated. 

Here are the related files.

JS:
```
success: function(theResponse){
	$("#formContainer-"+itemID).html(theResponse);
	divToggle ("#formContainer-"+itemID, "50,swing", 50);
},

function divToggle(ID, toggleSytle, duration) {	
	setTimeout(function () {
		$(ID).slideToggle(toggleSytle);	
	}, duration);
}
```

HTML:
```
<div id="formContainer-1" class="slidingForm" style="display: block;">

	<form id="editForm-1" name="editForm-1" method="post" action="">
		<div>
		   <select data-placeholder="Choose a Country..." class="chosen-select" tabindex="2">
		    <option value=""></option>
		    <option value="United States">United States</option>
		    <option value="United Kingdom">United Kingdom</option>
		    .
		    .
		    <option value="Zimbabwe">Zimbabwe</option>
		  </select>
		</div>

		<script type="text/javascript">
			var config = {
				'.chosen-select'           : {},
				'.chosen-select-deselect'  : {allow_single_deselect:true},
				'.chosen-select-no-single' : {disable_search_threshold:10},
				'.chosen-select-no-results': {no_results_text:'Oops, nothing found!'},
				'.chosen-select-width'     : {width:"95%"}
			}
			for (var selector in config) {
				$(selector).chosen(config[selector]);
			}
		</script>

		<div id="formButtons-1" class="formButtons">
			<button type="button" name="cancelButton" class="sharedButton cancelButton imgCancel" title="Cancel">Cancel</button>
			<button type="button" name="saveButton" class="sharedButton saveButton   imgSubmit" title="Save">Save</button>
		</div>
	</form>
</div>

```
CSS:
```
.slidingForm {
	display:none;
	float:left;
	width:100%;
	margin:15px 0 5px 0;
}
```

If I do the following changes, then it looks better, but ofcourse i loose the toggleSlide function.
![image_4](https://cloud.githubusercontent.com/assets/18124572/14087523/3af667d8-f4df-11e5-9dc1-5b8228bd991f.jpg)
![image_5](https://cloud.githubusercontent.com/assets/18124572/14087524/3af738ac-f4df-11e5-9938-79caee34a2ba.jpg)

JS:
```
success: function(theResponse){
	$("#formContainer-"+itemID).html(theResponse);
//	divToggle ("#formContainer-"+itemID, "50,swing", 50);
},
```

CSS:
```
.slidingForm {
	display:block;
	float:left;
	width:100%;
	margin:15px 0 5px 0;
}
```

**Comment by tjschuck** [comment] 2016-03-28 21:34
I think this is ultimately a duplicate of #2332 -- please try the workaround posted there.

**Closed by tjschuck** 2016-03-28 21:34 UTC

**Comment by sukrub** [comment] 2016-03-29 00:07
Thank you for your response. That fixed the major problem. I have changed the JS as fallows.
```
		<script type="text/javascript">
			var config = {
				'.chosen-select'           : {},
				'.chosen-select-deselect'  : {allow_single_deselect:true},
				'.chosen-select-no-single' : {disable_search_threshold:10},
				'.chosen-select-no-results': {no_results_text:'Oops, nothing found!'},
				'.chosen-select-width'     : {width:"95%"}
			}
			for (var selector in config) {
				$(selector).chosen(config[selector]);
			}
			$(".chosen-select").chosen('destroy');
			$(".chosen-select").chosen({width: "482px"});
		</script>
```

Now each entry floats left.
![image](https://cloud.githubusercontent.com/assets/18124572/14093977/0c0d2eb6-f507-11e5-85a5-9f4f30d7ec2f.png)

What can I do to remedy that. I also would like to be able to change the height, distance between entries, colors etc. Do I do that with straight CSS with the help of inspector. Or do I need to use JS controls like I did here with the width.

Is there a documentation that you can direct me?

**Comment by sukrub** [comment] 2016-03-29 14:41
I figured it out. I do not know if this is the best way to deal with it. But I am posting it here for others to possibly benefit.

I made modifications to chosen-sprite.png for the up/down arrows, and the magnifying glass
![chosen-sprite](https://cloud.githubusercontent.com/assets/18124572/14111725/acf76b9c-f580-11e5-8976-4e508efd9888.png)
and made changes in chosen.css on the following tags.You may like to leave chosen.css as it is, and over-write the few tags on your own css. Just play with background: url entries in the following tags

For corner arrows:
`.chosen-container-single .chosen-single div b`

For Magnifier:
`.chosen-container-single .chosen-search input[type="text"]`


I did the following entries to my css file (not the chosen.css)

```
.active-result {
	float:none;
	width:100%;
}

.chosen-single {
	height:38px !important;
	padding:4px 0 !important;
/*	border:1px solid red !important;	*/

}
.chosen-single span {
	color:#222 !important;
	padding:2px 9px !important;
	font: normal 1.35em 'Hind', sans-serif !important;
}

.chosen-single div {
/*	border:1px solid red !important;	*/
}

.chosen-results {
	font: normal 1.25em 'Hind', sans-serif !important;
}

.chosen-search input{
	height:35px !important;
	font: normal 1.25em 'Hind', sans-serif !important;
	color:#AAA !important;
/*	border:1px solid red !important;	*/
}
```
