### ISSUE TITLE
chosen-sprite.png not displayed for multiple select

### ISSUE THREAD

**Issue by nevf** [harvesthq/chosen#291] opened 2011-10-07 22:17 UTC
I've just noticed that the chosen-sprite.png (drop-down arrow) is not displayed for multiple select and the select styling also differs from the single select. It seems to me that the user would better identify multiple selects if they included the drop-down arrow. 

Is this not included for a specific reason and if not I'd like to see it included in a future update if possible.

Many thanks for developing this very nice plugin.

-Neville, http://www.surfulater.com

**Comment by patawa91** [comment] 2015-08-21 14:16
Is having the arrow on multi select something that could possibly be pulled in if it was implemented cleanly? Is it in the spirit of the project? I am considering submitting a pull request. Thanks

**Comment by tjschuck** [comment] 2015-08-21 15:01
I don't know what @pfiller is talking about -- the down arrow is definitely not included on multiselects.  You can see it on http://harvesthq.github.io/chosen/

Reopening, and pinging @mlettini

**Comment by patawa91** [comment] 2015-08-21 15:18
@tjschuck do you know if there is a fork or pull request where someone has attempted this. I implemented it for another project, and I'm considering submitting a pull request. I'd like to look how someone else has done it

**Comment by mlettini** [comment] 2015-08-21 16:08
The down arrow was never included on the multi-select. It was designed to look like an input with an autocomplete feature, not a select box you can scroll through (even though it has that functionality).

There is no bug/issue here, just a feature request. If someone was to open a PR for it, it should be optional.

**Comment by mrguruo** [comment] 2015-12-11 02:07
+1 request for this feature

**Comment by pfiller** [comment] 2016-06-03 20:37
Ok, so @mlettini says they're designed to look different and I'm ok with that. They _should_ look different!

Closing.

**Closed by pfiller** 2016-06-03 20:37 UTC
Labels: CSS, Feature Request

**Comment by MarcusSilvaBH** [comment] 2016-10-28 22:15
I'm having trouble to display the arrows and the magnifying glass even in single select!
Why?

**Comment by tslatt** [comment] 2017-10-18 21:07
My client also wants an arrow on the multi-select. With so many people wanting this and it still being asked for 6 years after the first request, can't it be an optional feature? Or, could one of you guys who implemented it yourself please post your code for everyone else who needs this?

**Comment by masoud1367** [comment] 2018-02-14 07:09
https://cdnjs.com/libraries/chosen

**Comment by DanKing123** [comment] 2018-05-09 11:44
I'm having the same problem. I don't understand why you wouldn't make the arrow optional at least, since it's a thing that so many people want and it makes it much more obvious and easier to use.

I have a solution here for anyone who needs it, but it's _very_ hacky I'm afraid!

CSS:
<pre>
.chosen-container-multi ul.chosen-choices:after {
    content: '';
    background-image: url(chosen-sprite.png);
    background-position-x: 0px;
    background-position-y: 2px;
    display: block;
    position: absolute;
    top: 0;
    right: 0;
    width: 18px;
    height: 25px;
    cursor: pointer;
}

.chosen-container-multi.chosen-with-drop ul.chosen-choices:after {
    background-position-x: -18px;
}
</pre>

The above will make the arrow appear in the correct orientation depending on whether the drop list is open or closed.

The tricky part is making it clickable in order to close the drop list. This is where it got _really_ hacky I'm afraid:

<pre>
// chosenify your drop list (mine is called "myMultiSelect") and then:

// Need to register a handler to fire *before* Chosen's mousedown event, and detect the current
// state of the drop down plus whether the arrow has been clicked. Then set a flag accordingly.
var justClosed;
$("#myMultiSelect_chosen").mousedown(function(e) {
    var elem = $(this);
    // Note that this depends on the width of the arrow (18 pixels) defined in the CSS above
    justClosed
        = elem.hasClass('chosen-with-drop') && e.pageX >= elem.position().left + elem.width() - 18;
});
// Need to hack jQuery (I'm using 1.10.2) to get in before Chosen's event handler - NOTE: this may
// break in later jQuery versions!
var mousedownHandlers = $._data($("#myMultiSelect_chosen").get(0), 'events').mousedown;
mousedownHandlers.splice(0, 0, mousedownHandlers.pop());

// Close the dropdown (if needed) from the click handler (if we do it earlier than this, it will
// interfere with other Chosen functionality).
$("#myMultiSelect_chosen").click(function(e) {
    if (justClosed) {
        $("#myMultiSelect").trigger('chosen:close');
    }
});
</pre>

Caveat: THIS MAY BREAK WITH FUTURE RELEASES OF CHOSEN OR JQUERY!!

**Comment by DanKing123** [comment] 2018-05-09 12:33
I'm having the same problem. I don't understand why you wouldn't make the arrow optional at least, since it's a thing that so many people want and it makes it much more obvious and easier to use.

I have a solution here for anyone who needs it, but it's _very_ hacky I'm afraid!

CSS:
<pre>
.chosen-container-multi ul.chosen-choices:after {
    content: '';
    background-image: url(chosen-sprite.png);
    background-position-x: 0px;
    background-position-y: 2px;
    display: block;
    position: absolute;
    top: 0;
    right: 0;
    width: 18px;
    height: 25px;
    cursor: pointer;
}

.chosen-container-multi.chosen-with-drop ul.chosen-choices:after {
    background-position-x: -18px;
}
</pre>

The above will make the arrow appear in the correct orientation depending on whether the drop list is open or closed.

The tricky part is making it clickable in order to close the drop list. This is where it got _really_ hacky I'm afraid:

<pre>
// chosenify your drop list (mine is called "myMultiSelect") and then:

// Need to register a handler to fire *before* Chosen's mousedown event, and detect the current
// state of the drop down plus whether the arrow has been clicked. Then set a flag accordingly.
var downArrowClicked;
$("#myMultiSelect_chosen").mousedown(function(e) {
    var elem = $(this);
    // Note that this depends on the width of the arrow (18 pixels) defined in the CSS above
    downArrowClicked
        = elem.hasClass('chosen-with-drop') && e.pageX >= elem.position().left + elem.width() - 18;
});
// Need to hack jQuery (I'm using 1.10.2) to get in before Chosen's event handler - NOTE: this may
// break in later jQuery versions!
var mousedownHandlers = $._data($("#myMultiSelect_chosen").get(0), 'events').mousedown;
mousedownHandlers.splice(0, 0, mousedownHandlers.pop());

// Close the dropdown (if needed) from the click handler (if we do it earlier than this, it will
// interfere with other Chosen functionality).
$("#myMultiSelect_chosen").click(function() {
    if (downArrowClicked) {
        // Use timeout to ensure all other current processing has completed before closing the dropdown
        // - without this it doesn't work in IE/Edge
        setTimeout(function() { $("#myMultiSelect").trigger('chosen:close'); });
    }
});
</pre>

Caveat: THIS MAY BREAK WITH FUTURE RELEASES OF CHOSEN OR JQUERY!!

**Comment by R-W-C** [comment] 2023-10-20 22:26
To everybody who thinks chosen-sprite.png is (still) missing, you are right.

It is not in the archive you downloaded "Image-Select-master.zip".  If you open "example.html"" in your browser, you end up with the following error messages:

Failed to load resource: net::ERR_FILE_NOT_FOUND chosen.css:1 
Failed to load resource: net::ERR_FILE_NOT_FOUND jquery.min.js:1     
Failed to load resource: net::ERR_FILE_NOT_FOUND chosen.jquery.js:1 
        
You have to download "chosen" first from this website: https://github.com/harvesthq/chosen

But think twice before using it. It is not actively maintained, last modified 5 years ago and there are 250 (!) open issues.
