### ISSUE TITLE
Don't hide dropdown after selection on a multiple select

### ISSUE THREAD

**Issue by jnsandrew** [harvesthq/chosen#2310] opened 2015-04-10 11:38 UTC
I couldn't see an option for this, and I didn't have much luck using the events / triggers either, but is it possible to not hide the dropdown after choosing an option. I currently have a multiple select with a lot of options, and it's painful to open the dropdown after a selection and scroll the whole way down again.

Similar to #21 - but for me holding CMD doesn't keep the dropdown open.

**Comment by qwelyt** [comment] 2015-04-13 09:43
Care to post a jfiddle with an example and some info on your browser?
I'm unable to reproduce the behaviour. Ctrl+Click keeps the options open for me.

**Comment by ondefar** [comment] 2015-04-15 12:39
this was posted on stackexchange, and works like a charm:
`var chosen = $('.yourChosenclass').chosen().data('chosen');
var autoClose = false;
var chosen_resultSelect_fn = chosen.result_select;
chosen.search_contains = true;

chosen.result_select = function(evt) 
{
    var resultHighlight = null;

    if(autoClose === false)
    {
        evt['metaKey'] = true;
        evt['ctrlKey'] = true;

        resultHighlight = chosen.result_highlight;
    }

    var stext = chosen.get_search_text();

    var result = chosen_resultSelect_fn.call(chosen, evt);

    if(autoClose === false && resultHighlight !== null)
        resultHighlight.addClass('result-selected');

    this.search_field.val(stext);               
    this.winnow_results();
    this.search_field_scale();

    return result;
 };
`

**Comment by jnsandrew** [comment] 2015-04-15 13:52
Thanks for the response - just an update, I'm stuck on other projects at the moment for another week probably so can't try this until I'm back in the office.

**Comment by periyasamy25** [comment] 2015-05-07 15:07
I need the following for my dropdown.
1.Don't hide dropdown after selection on a multiple select
2.If cilck the value it should be selected and click again it should be unselected and also don't want to hide dropdown.

help me

**Comment by BarisW** [comment] 2015-08-07 11:17
Thanks @ondefar. I used you code to fix my issue. Works great, thanks for sharing!

**Comment by tjschuck** [comment] 2016-01-27 16:31
Thanks to everyone here for your workarounds.  This issue is a duplicate of #1546, though, so I'm closing this one in favor of that one.  Please leave any additional feedback you may have there.

Thanks again!

**Closed by tjschuck** 2016-01-27 16:31 UTC

**Comment by chaitanya-nyros** [comment] 2018-01-24 11:01
@ondefar Works like a charm :+1:
