### ISSUE TITLE
Enable "and" searches.

### ISSUE THREAD

**Issue by koenpeters** [harvesthq/chosen#1917] opened 2014-04-29 17:50 UTC
It would be nice if the search would somehow support the possibility of doing && searches. Of you'd type "hello world" it would match all options that have both "hello" and  "world" in it's text. So it would for example match both "this is an hello world example" and "just saying hello to the world".

**Comment by koenpunt** [comment] 2016-10-03 09:05
Duplicate of #677

**Closed by koenpunt** 2016-10-03 09:05 UTC
Labels: Feature Request, Search
