### ISSUE TITLE
how to open dropdown upside

### ISSUE THREAD

**Issue by jignesh87** [harvesthq/chosen#2339] opened 2015-06-05 09:06 UTC
how to open dropdown upside?

**Comment by kevin-brown** [comment] 2015-06-05 13:19
This appears  to be a duplicate of https://github.com/harvesthq/chosen/issues/155.

**Comment by d07RiV** [comment] 2015-06-05 14:39
Not possible. I modified mine to do that but it was quite a lot of work, since the default styles don't support it, either.

**Comment by tjschuck** [comment] 2015-06-05 14:42
Yep, duplicate of https://github.com/harvesthq/chosen/issues/155.  Leave any feedback you have there.

**Closed by tjschuck** 2015-06-05 14:42 UTC
