### ISSUE TITLE
Fire chosen:showing_dropdown after winnowing?

### ISSUE THREAD

**Issue by gwcoffey** [harvesthq/chosen#2380] opened 2015-07-28 19:48 UTC
I'm not sure if this is a bug or a feature request, and I'm curious if a pull request would be accepted.

I do some DOM twiddling to the choice popup on chosen:showing_dropdown. This works great when you click/tab into the field. But if the user types into the input field, initiating a search, the already-showing popup is winnowed and there's no event I can listen to to tweak the results.

I can see doing this in two ways:

1: instead of firing chosen:showing_dropdown in results_show you could do it in winnow_results. This would trigger the event every time the popup is updated, not just when it is first shown. This is arguably dangerous because it changes existing behavior. (I will note that pressing down-arrow after the search triggers chosen:showing_dropdown now, which is why I say perhaps this is actually a bug).

2: introduce a new event, i.e., chosen:showing_results, that is triggered after every winnow.

Would a pull request for either of these be accepted?

Thanks!

Geoff

**Comment by pfiller** [comment] 2016-06-07 16:42
Duplicate of #2372

**Closed by pfiller** 2016-06-07 16:42 UTC
