### ISSUE TITLE
clicking controller removes cursor

### ISSUE THREAD

**Issue by tyhatcher** [harvesthq/chosen#2197] opened 2015-01-15 18:35 UTC
When using the multiple select, if you click the controller after it already has focus, the cursor disappears and you cannot type/search. You have to click away from the controller and back in to be able to type again.

**Comment by tjschuck** [comment] 2015-01-15 19:34
I _think_ this is a duplicate, but I can't find the original anywhere...

Anyway, I think the problem is this:

![](http://monosnap.com/image/7ztPTW835a9Mk6BKqMgaae1FoHixUh.png)

i.e. the `input` box is much smaller than the visual "input" area.  Clicking to the right of the input will remove focus from the actual `input`.

Feel free to submit a pull request if you have a fix!

**Comment by tyhatcher** [comment] 2015-01-15 19:40
Cool, thanks.

**Comment by pfiller** [comment] 2016-06-07 04:09
Duplicate of #1729

**Closed by pfiller** 2016-06-07 04:09 UTC
