### ISSUE TITLE
Shift+select

### ISSUE THREAD

**Issue by qwelyt** [harvesthq/chosen#2226] opened 2015-02-06 10:43 UTC
Our product is used in schools where there are lots of students and teachers. In our system you can select these to be included in groups. With the standard HTML multi-select you can do the handy thing of selecting the first value, holding shift, and selecting the last value to mark everyone as selected. This is not possible with Chosen as I have experianced. You can hold Ctrl and click on elements, but that only allows you to select more options while still keeping the option-box open.

So, is there any possibility to do the shift-select that the ordinary multiselect supports? Or will our users have to do *lots* of clicks to get everything? (the last one I heard were about to select 108 people out of a list of 120, fun!)

**Comment by tjschuck** [comment] 2015-02-06 18:43
Not currently supported, and this issue is a duplicate of #135 -- closing this in favor of that one.  Feel free to leave any additional feedback you have there.

There's also PR #1563 which attempts to add it, but it was never reviewed/merged, and is pretty out of date with Chosen master.  If you absolutely need this functionality, you could use their patched out-of-date version of Chosen.

Additionally, you could ask on that PR for the original author to rebase their contributions against master to get it up to date.  If they're unable to, you could try to rewrite their patches yourself against master and open a new PR (however, no guarantees that it would be reviewed/merged -- your standard OSS warnings apply).

**Closed by tjschuck** 2015-02-06 18:43 UTC

**Comment by ComeBurguburu** [comment] 2015-02-06 19:45
:+1: needed

**Comment by casph** [comment] 2015-07-30 14:57
needed
