### ISSUE TITLE
Time lag when select a chosen dropdown on Firefox 35.0.1

### ISSUE THREAD

**Issue by tusharughade** [harvesthq/chosen#2244] opened 2015-02-19 11:43 UTC
Chosen drop down on Firefox 35.0.1, takes more time to show the options list, 
It works fine on all other version of Firefox, Chrome, IE & Safari

**Comment by tjschuck** [comment] 2015-02-19 16:15
What version of Chosen?  And what OS did you test it on?

Is it for _any_ Chosen select?  Does the number of options affect it?

Can you link to a publicly accessible page (or a [Fiddle](http://jsfiddle.net)) that shows the issue so we can attempt to reproduce?  (Alternatively, does it happen on the [Chosen homepage itself](http://harvesthq.github.io/chosen/)?)

**Comment by tusharughade** [comment] 2015-02-20 05:26
I am using Chosen v1.3.0 which I have test it on Windows 7.
please find the screen below of the chosen selector
![chosen](https://cloud.githubusercontent.com/assets/9526673/6281817/41138368-b8ee-11e4-996d-fe2b9119cfde.JPG)
You can find the issue on Chosen homepage itself (by only using Firefox 35.0.1)

**Comment by tjschuck** [comment] 2015-02-20 16:35
Cannot reproduce on OS X, Firefox 35.0.1.  Seems like it might be Windows specific.

**Comment by pfiller** [comment] 2016-06-07 04:23
Firefox is an auto-updating browser which is currently on version 46. I think it's safe to close this, but would welcome someone re-opening if its still reproducible.

**Closed by pfiller** 2016-06-07 04:23 UTC
