### ISSUE TITLE
Chosen docs should reference built files

### ISSUE THREAD

**Issue by martinburch** [harvesthq/chosen#2661] opened 2016-08-03 20:58 UTC
Hi, I'm not sure if this is the right place for documentation issues, but I was confused by the download link in https://harvesthq.github.io/chosen/

It just links to the releases of this repo, which seem to be for development only, and not a quick way to use Chosen in production.

I recommend adding a link to the built javascript and css files in the chosen-package repo and/or the CDN link https://cdnjs.com/libraries/chosen

**Comment by tjschuck** [comment] 2016-08-03 21:33
@martinburch The [releases page](https://github.com/harvesthq/chosen/releases) does typically include the pre-compiled, production-ready versions.  See the [`chosen_v1.6.1.zip` file on this release](https://github.com/harvesthq/chosen/releases/tag/v1.6.1).

However, the latest release [seems to be missing this packaged ZIP and only has the source code](https://github.com/harvesthq/chosen/releases/tag/v1.6.2).  @koenpunt — known issue?

**Comment by tjschuck** [comment] 2016-08-03 21:35
(This also seems to be a duplicate of #2660, but that's already closed.)

**Comment by koenpunt** [comment] 2016-08-03 21:36
My bad, forgot to add the zip to the release. Should be all good now

**Comment by koenpunt** [comment] 2016-08-03 21:39
Oh wait, incorrect zip, give me a minute

**Comment by koenpunt** [comment] 2016-08-03 21:48
I cheated on the git tag, but it's up how it should now, and the npm release is now also a fact.

**Comment by martinburch** [comment] 2016-08-03 21:48
Thank you!

**Closed by koenpunt** 2016-08-03 21:48 UTC
