### ISSUE TITLE
Ajax Feature

### ISSUE THREAD

**Issue by rahulcse1** [harvesthq/chosen#2625] opened 2016-06-11 10:00 UTC
is there ajax support ? I have a scenario where I am having a big list of drop down. I don't want to show the drop down until user searches it.

**Comment by kevin-brown** [comment] 2016-06-11 15:51
This appears to be a duplicate of https://github.com/harvesthq/chosen/issues/79.

**Comment by koenpunt** [comment] 2016-09-16 10:08
Duplicate of #79

**Closed by koenpunt** 2016-09-16 10:08 UTC
Labels: Duplicate
