### ISSUE TITLE
Make the select masked but not hidden.

### ISSUE THREAD

**Issue by kamlekar** [harvesthq/chosen#2636] opened 2016-06-27 10:38 UTC
I am seeing that the chosen library is hiding the actual field i.e select field. In my case, I want the select field to get masked instead of getting hidden. 

Because, if the select field gets hidden, I am unable to use the HTML 5 validations. I am not planning to fix this by including any validation plugin which will be overkill, imo.

Please help.

### Steps to reproduce

HTML

    <select class="custom-select" required name="tags[]">
        <option value="1">Jon</option>
        <option value="1">Jon</option>
        <option value="1">Jon</option>
    </select>

After including the plugin. 

    $('.custom-select').chosen();

### Environment

  - **Chosen 1.6.1**

  - **jQuery 2.2.4**

  - **Browser and Version**: Chrome 51.0.2704

  - **OS and Version**: Mac OSX 10.11

**Comment by koenpunt** [comment] 2016-09-16 09:05
Duplicate of #515

**Closed by koenpunt** 2016-09-16 09:05 UTC
