### ISSUE TITLE
After opening several times dialog with select chzn-select the search doesn't work

### ISSUE THREAD

**Issue by gioviarena** [harvesthq/chosen#2556] opened 2016-02-29 15:11 UTC
Hello,
I have a problem with chosen plugin.
After opening 7/8 times same dialog UI with the same select, I cannot type anithing in the input text for the search. The focus is set over there, but if I type any kind of character, it doesn't work.
May anyone help me?
Many thanks in adavance!!

**Comment by gioviarena** [comment] 2016-02-29 15:24
I am using Version 0.9.7 of chosen.jquery.min.js and v1.7.2 of jQuery.

**Comment by tjschuck** [comment] 2016-02-29 23:07
Version 0.9.7 was released more than 4 years ago, and there have been [many releases since](https://github.com/harvesthq/chosen/releases).  Your best bet is to upgrade to the current version.

If you need to stay on your version for whatever reason, you'll probably have to try somewhere like [StackOverflow](http://stackoverflow.com/) instead for support on your issue; the GitHub issue tracker is intended for bug reports and pull requests for future versions, not long outdated ones.  You'll be more likely to get a quick and useful answer there.

**Comment by koenpunt** [comment] 2016-03-01 07:51
> the GitHub issue tracker is intended for bug reports and pull requests for future versions

I think this not always true, although for Chosen the upgrade path is minimal. And if it is a valid bug, why not fix it (if possible within a certain time constraint)

**Comment by gioviarena** [comment] 2016-03-01 08:28
Hello,
I have updated the chosen plugin with the latest version but the behavior is the same.
May you please reopen the issue?
Many thanks

**Comment by tjschuck** [comment] 2016-03-01 20:58
@gioviarena What browser, browser version, OS, and OS version are you using?

Can you please link to a publicly accessible page (or a [Fiddle](http://jsfiddle.net)) that shows the issue so we can attempt to reproduce?  Alternatively, confirm that the [Chosen demo page](http://harvesthq.github.io/chosen/) shows the issue.  It does not for me.

**Comment by gioviarena** [comment] 2016-03-02 11:24
Hello,
I am using Firefox 44.0.2 and Google Crome 48.0.2564.116 m. As OS I have Windos Vista.
I have prepared a quick  demo environment here:
http://test.globalkom.net
Login with
user: test
pwd: test

Then press button "ACQUISTO" and then button "ORDINE D'ACQUISTO". 

For opening the UI dialog with select chosen that creates the issue, go to the “binocular” button under “Codice Articolo”. Type something in the first select like “W” or “1” and then select one string of the list.
Repeat the process adding a new line (you should press button “+ Riga” in the top of the page, or press key “+” of the keyboard one the focus is on an input text.
I am not sure the bug is verified, sometimes it appears after adding 7/8 line, sometimes after 10 lines. So please verify the chosen behavior with several lines.

I am attaching a guide.doc for the steps with screen shots and also a video for show you the behavior (at the end I can't write in search input field).

Many tanks in advance!
[guide.docx](https://github.com/harvesthq/chosen/files/154618/guide.docx)

https://youtu.be/Quq2VNKrkag

**Comment by koenpunt** [comment] 2016-03-02 11:36
Nice bells in the background ;) I noticed that just opening and closing details for the same row over and over again results in the same behavior.

**Comment by koenpunt** [comment] 2016-03-02 11:47
While testing a little more, I suspect that some event are triggered multiple times; which results in duplicate rows.

Have a look at my little screencast and let me know if this is the expected behavior or not:

http://recordit.co/0SbgAwvpAE

**Comment by gioviarena** [comment] 2016-03-02 11:58
Yes, it is correct. It is due to a user require in order to select the item by product code, without specify the color. Same product may have different colors, so the system add 1 line per color.
You can see that because the product 1234 is available in green (verde) and in fucsia.

Thanks!

**Comment by koenpunt** [comment] 2016-03-02 12:36
Tested a little further, and it turns out that the issue is an effect of jQuery UI. When I remove the keypress event of jQuery UI, I can use the input again: 

http://recordit.co/Wk6zyGRNz4

**Closed by koenpunt** 2016-03-02 12:36 UTC
Labels: Awaiting Reply

**Comment by gioviarena** [comment] 2016-03-02 13:49
So it means that chosen plugin doesn't work 100% with jQuery UI? Those are events properly of jQuery. I have tried, in my localhost, to delete from the page all event listener. 
But anyway those listeners are there.
What do you suggest to do?
Thanks in advance

**Comment by koenpunt** [comment] 2016-03-02 18:11
> So it means that chosen plugin doesn't work 100% with jQuery UI? 

Or doesn't jQuery UI doesn't work with Chosen? ;)

Anyway, I read it could have something to do with the z-index, and that is has been fixed in newer versions of jQuery UI. So your best guess is updating jQuery UI to a more recent one.
