### ISSUE TITLE
List hidden when using EasyUI dialog/panel

### ISSUE THREAD

**Issue by PaulMcGuinness** [harvesthq/chosen#2875] opened 2017-08-30 14:29 UTC
### Steps to reproduce

Use a 'chosen' box inside an EasyUI panel/dialog container.

When the chosen box is selected, the list is hidden (or partially hidden)

### Expected behavior

List is shown on top of all elements

### Actual behavior

Hidden behind the EasyUI Panel (see image below)

### Environment

  - *1.8

  - 1.8.x

  - All

  - n/a

### Additional information

I think that this can be dealt with in one of the following ways, but am unsure what is the best way to do this.....

1. Either allow 'overlap' of all visible items
2. A specific CSS class to allow it to be 'on top'
3. A property to offset the display list so that when it opens, "top" is adjusted, then adjusted back

![image](https://user-images.githubusercontent.com/124485/29877525-c655bd9a-8d97-11e7-9872-daf7f22801f3.png)

**Comment by tjschuck** [comment] 2017-08-30 15:13
This is effectively a duplicate of https://github.com/harvesthq/chosen/issues/86 — closing this in favor of that.  Feel free to leave any additional feedback you have there.

**Closed by tjschuck** 2017-08-30 15:13 UTC
