### ISSUE TITLE
Don't close dropdown when a selection is clicked

### ISSUE THREAD

**Issue by Lightheaded** [harvesthq/chosen#2515] opened 2016-01-27 06:21 UTC
Is it possible to leave the dropdown open when an option is selected in multiple mode?

**Comment by tjschuck** [comment] 2016-01-27 16:30
@Lightheaded This is not currently possible to force with Chosen, however if you hold <kbd>CMD ⌘</kbd> or <kbd>CTRL</kbd> while clicking, it will stay open.

This request is a duplicate of #1546 — please leave any feedback you have there!

**Closed by tjschuck** 2016-01-27 16:30 UTC
