### ISSUE TITLE
chosen select does not work in tables when dynamically creating rows

### ISSUE THREAD

**Issue by KillSwitch666** [harvesthq/chosen#2424] opened 2015-09-20 11:01 UTC
can't access dynamically created select menus.
using latest JQuery , FF 40.0.3, windows 7 Ultimate 64bit.

PS.
using: $("[class^='chosen_select_']").chosen({

UPDATE:
created a fiddle
https://jsfiddle.net/vwgyt42u/

**Comment by mav2287** [comment] 2015-09-30 16:12
I dealt with this same issue the other day. The problem is that when you pull the html you are pulling the select AND the chosen box the was created for it. Now you have identical copies and that is bad. What you want to do is just copy the select and then apply chosen to it to make it a chosen drop. If you really want to use HTML you would need to strip out the chosen box and then re-apply chosen to it.

**Comment by tjschuck** [comment] 2015-09-30 16:27
> If you really want to use HTML you would need to strip out the chosen box and then re-apply chosen to it.

Note that there is a `$("#my-select").chosen("destroy")` to strip Chosen, but it's undocumented -- see #2290 :sob: (PR to document it gladly accepted!).

After that, you can re-initialize with `$("#my-select").chosen()`.

Closing per @mav2287's workaround -- thanks @mav2287!

**Closed by tjschuck** 2015-09-30 16:27 UTC

**Comment by mav2287** [comment] 2015-09-30 16:33
tjschuck thanks for the heads up on the chosen destroy!  Please do add that to the docs I can think of at least 4-5 places in my code alone I could have used it rather than a workaround.

**Comment by tjschuck** [comment] 2015-09-30 19:50
@mav2287 See #2436!

**Comment by KillSwitch666** [comment] 2015-10-01 09:49
@mav2287 thanks for the comment i already solved it by using destroy as mentioned by @tjschuck, it just drove me mad until i figured it out.
i didn't had the chance to update it here because the project i was working on got delayed because of this and i had to work extra hours and fast, so i forget all about this post.
anyway here is an updated fiddle with destroy method implemented: https://jsfiddle.net/vwgyt42u/1/

**Comment by stojko75** [comment] 2017-01-27 22:15
It's worth mentioning, you need to destroy it **before** row cloning and **after** cloning, initialize again.

**Comment by Rig-ved** [comment] 2018-03-05 13:21
Thanks for the info shared .. Need to destroy the chosen and then initialize :) worked wonders

**Comment by sudhir600** [comment] 2019-07-12 06:57
Here is the full working code - (Gist) [dynamically_chosen.html](https://gist.github.com/sudhir600/a5e5c69097187eb576c54d714d63c717) and [JsFiddle ](https://jsfiddle.net/sudhir600/2f71xmLz/)
