### ISSUE TITLE
Chosen framework not responding in Firefox

### ISSUE THREAD

**Issue by satykrishna** [harvesthq/chosen#2748] opened 2016-11-08 19:37 UTC
Summarize your issue 
--------------------------------------

Facing an error with respect to chosen framework as shown in below image. 

![capture](https://cloud.githubusercontent.com/assets/9643234/20113592/fadbd93a-a5be-11e6-8760-c904ddf742da.PNG)

### Steps to reproduce

Tell us how to reproduce this issue.

  1.Initially these drop downs are empty fields

  2. An ajax call will be send to server and fetch 4000 records as shown below
     let say sample data is  data:[a, b, c, d, e, f, g....... ]. 

  3. dropdown will be populated with each element in the array 

  4. The firefox application will become unresponsive and hangs with the error message as shown above.

 The corresponding code is as shown below.

HTML:
<select class="chosen-select form-control form-control-sm right inputGroup" id="A">
</select>

javascript/jquery

function appendToChosen(ele, id, value) {
	$(ele).append("<option value='" + id + "'>" + value + "</option>").trigger("chosen:updated");
}

var inputField = '#A';
	$.getJSON("url",  function(data) {
		$(inputField).empty();
		appendToChosen('#A, '', 'select');
		$('#A option[value=""]').attr("selected", true);
		$.each(data, function(index, value) {
			if (value != null) {
				appendToChosen('#A', value.trim(), value.trim());
			}
		});
	});

### Expected behavior
  Ideally I must be able to see a working dropdown which is dynamically populated with all the options

### Actual behavior
Browser hangs with the error message as shown in the above image.

### Environment

  - **Chosen Version**:  Version 1.5.1

  - **jQuery or Prototype Version**:  v1.12.4 

  - **Browser and Version**: firefox 49.0.2

  - **OS and Version**: Windows and Ubuntu and Mac

**Comment by koenpunt** [comment] 2016-11-08 21:10
Try adding them all first, and then trigger `chosen:updated` only once. And as this is not a bug, or related to common usage, I'm going to close this.

**Closed by koenpunt** 2016-11-08 21:10 UTC

**Comment by koenpunt** [comment] 2016-11-08 21:14
BTW, is this the line 113 in your version of Chosen too; https://github.com/harvesthq/chosen-package/blob/v1.5.1/chosen.jquery.js#L113 ?

**Comment by satykrishna** [comment] 2016-11-09 00:49
No.. Plese find below code at line 113

 SelectParser.select_to_array = function(select) {
    var child, parser, _i, _len, _ref;
    parser = new SelectParser();
    _ref = select.childNodes;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {  //Line 113
      child = _ref[_i];
      parser.add_node(child);
    }
    return parser.parsed;
  };
