### ISSUE TITLE
Multi-select broke on iPhone 6

### ISSUE THREAD

**Issue by hallmatt** [harvesthq/chosen#2259] opened 2015-03-05 22:12 UTC
When I load up the Chosen site (http://harvesthq.github.io/chosen/) and use the "Multiple Select" example, it seems as if the functionality is not working correctly when I deselect a country. Here's the steps I take:

1. Using the Multiple Select example, select multiple countries (i.e. United States, Afghanistan, and Algeria). Click the Done button to finalize the selection. 
2. Reselect the drop down to change your selections, and deselect one or more of the countries. This will put the deselected country into the dropdown as if that country was actually selected. If you hit the Done button, it'll show that Chosen has just selected that country instead of deselecting it.

Additionally, you could just select and deselect countries randomly to see the issue. 

This functionality occurred on an iPhone 6 and 4s, both using iOS 8. 

An iPad Air with iOS 8 and an older Android Galaxy S3 phone both worked fine.

Any thoughts?

**Comment by tjschuck** [comment] 2015-03-05 22:15
@hallmatt Chosen should be completely disabled for the iPhone (as well as all non-tablet mobile devices).  Are you seeing the Chosen mutliselect UI, or the native iOS UI?

Closing pending more info.

**Closed by tjschuck** 2015-03-05 22:15 UTC

**Comment by tjschuck** [comment] 2015-03-05 22:17
Here's the regex that disables Chosen on iPhone: https://github.com/harvesthq/chosen/blob/e41fa15ae620559443b4e8132f18e98039917448/coffee/lib/abstract-chosen.coffee#L275-L282

**Comment by hallmatt** [comment] 2015-03-05 22:26
I'm not exactly sure what the native UI looks like for that element, It does seem native, but it also seems like there might be some additional Javascript that's triggering this behavior. I'd be surprised if I found a bug in iOS...

Were you able to replicate this issue as well?

**Comment by tjschuck** [comment] 2015-03-05 22:27
Not on an iPhone 5S running iOS 8.  I was presented with the native select.

Were you using Safari, or another browser?

**Comment by hallmatt** [comment] 2015-03-05 22:39
I was using Safari. I opened up the iOS simulator in XCode and was able to replicate it with an iOS 4s, 5s, and 6 device. 

Here's a gif of how to replicate the issue:

![github](https://cloud.githubusercontent.com/assets/904874/6516251/5a99c5b6-c35e-11e4-92d7-2495c232e6b6.gif)

**Comment by tjschuck** [comment] 2015-03-05 22:43
That's the iOS native select, not Chosen.

**Comment by tjschuck** [comment] 2015-03-05 22:49
I can actually reproduce your issue on the left-hand-side select as well, which is _definitely_ not a Chosen select, since that's the example select.

Might be an iOS bug.  I recommend creating a [Fiddle](http://jsfiddle.net) to see if you can reproduce it with just a standalone multiselect in a clean environment, and if so, submit it to http://bugreport.apple.com

**Comment by hallmatt** [comment] 2015-03-06 13:58
Unfortunately the multiple select works in iOS 8 on this page, so I'm guessing it has something to do with how the select tag is rendered: http://www.htmlcodetutorial.com/forms/_SELECT_MULTIPLE.html

**Comment by hallmatt** [comment] 2015-03-06 13:59
Check that still broken. This is strange. It was working fine for a moment.

**Comment by susan-github** [comment] 2015-09-09 07:18
I tried to return "true" when call "browser_is_supported", I found the performance on mobile is OK.
Why disable this plugin on mobile? Is there has any disadvantage?
