### ISSUE TITLE
Multiselect drop down menu z-index issue

### ISSUE THREAD

**Issue by mik115** [harvesthq/chosen#1585] opened 2013-10-01 12:09 UTC
hi,
i have a multiselect with the drop down menu not at first level but under an
other div.
in the picture you can see the difference between the multiselect and a normal select (that is the behavior i'm after).

![schermata chosen](https://f.cloud.github.com/assets/2995032/1244905/1e48e120-2a92-11e3-807a-23cfdaa37f54.png)

there's some trick or workaround to obtain that?

Michele

**Comment by pfiller** [comment] 2016-06-04 20:37
It's not a `z-index` issue, it's an issue with the containing div having `overflow:hidden` set. This is a duplicate of #86.

**Closed by pfiller** 2016-06-04 20:37 UTC
