### ISSUE TITLE
Chosen options don't support title attribute

### ISSUE THREAD

**Issue by sdarisi** [harvesthq/chosen#2213] opened 2015-01-28 20:04 UTC
There's no way to add title (tooltip) attribute to chosen options. Here's a patch to support adding title if someone can apply, 

```
 coffee/lib/abstract-chosen.coffee | 2 ++
 coffee/lib/select-parser.coffee   | 1 +
 2 files changed, 3 insertions(+)

diff --git a/coffee/lib/abstract-chosen.coffee b/coffee/lib/abstract-chosen.coffee
index fcf6289..ad282ce 100644
--- a/coffee/lib/abstract-chosen.coffee
+++ b/coffee/lib/abstract-chosen.coffee
@@ -93,6 +93,8 @@ class AbstractChosen
     classes.push option.classes if option.classes != ""
 
     option_el = document.createElement("li")
+    if option.title
+      option_el.title = option.title
     option_el.className = classes.join(" ")
     option_el.style.cssText = option.style
     option_el.setAttribute("data-option-array-index", option.array_index)
diff --git a/coffee/lib/select-parser.coffee b/coffee/lib/select-parser.coffee
index c6289e8..4dd2172 100644
--- a/coffee/lib/select-parser.coffee
+++ b/coffee/lib/select-parser.coffee
@@ -32,6 +32,7 @@ class SelectParser
           value: option.value
           text: option.text
           html: option.innerHTML
+          title: option.title
           selected: option.selected
           disabled: if group_disabled is true then group_disabled else option.disabled
           group_array_index: group_position
```

**Comment by tjschuck** [comment] 2015-01-28 20:12
Duplicate of https://github.com/harvesthq/chosen/pull/1704 -- please leave any feedback you have there.

**Closed by tjschuck** 2015-01-28 20:12 UTC
