### ISSUE TITLE
Chosen size broken inside bootstrap accordion

### ISSUE THREAD

**Issue by lampi87** [harvesthq/chosen#2656] opened 2016-08-02 09:44 UTC
Hello,
If I add a chosen multiple select inside an accordion the size is not correctly calculated. Possible, but ugly fix is to destroy and recreate chosen each time accordion is shown, e.g.:
```javascript
$('#tableEditorFilter').on('shown.bs.collapse', function() {
    $('.chosen').chosen("destroy");
    $('.chosen').chosen().change();
});
```
If I use show.bs.collapse as trigger, style is still broken.

### Steps to reproduce

Setup panel (accordion) with bootstrap and chosen.
  1. Add multiple select to accordion
  2. Make accordion closed by default
  3. Click on accordion title to open it

![bildschirmfoto 2016-08-02 um 11 31 40](https://cloud.githubusercontent.com/assets/3034138/17324130/47f6ad6a-58a5-11e6-9ab0-cca66567d777.png)

### Environment

  - **Chosen Version**: v1.6.1

  - **jQuery or Prototype Version**: jquery v3.1.0

  - **Bootstrap Version**: jquery v3.3.7

  - **Browser and Version**: Chrome 51 

  - **OS and Version**: OSX

**Comment by koenpunt** [comment] 2016-08-02 09:50
This is a known issue, and has been discussed many times before. Duplicate of #92

**Closed by koenpunt** 2016-08-02 09:50 UTC
