### ISSUE TITLE
Form Reset and "Chosen:Updated" trigger

### ISSUE THREAD

**Issue by vaikoovery** [harvesthq/chosen#2293] opened 2015-03-30 07:13 UTC
As expected, 
$('select.has_chosen').val('').trigger('chosen:updated'); 
works well upon form reset.

However, when I have chosen content loaded dynamically, the above code will not work as expected.
I've tried, 
$('select.has_chosen').trigger('chosen:updated');
which works only after clicking on the RESET button twice.

What could be the possible solution? Or is there a solution already?

**Comment by vaikoovery** [comment] 2015-03-30 07:24
Got a workaround, however it would be great to avoid this patch.

$('#form_reset').click(function(e){
    setTimeout(function(){clearChosen()}, 200);
});
function clearChosen(){
    $('select.has_chosen').trigger('chosen:updated');
}

**Comment by pfiller** [comment] 2015-04-01 03:11
Without seeing a working example of [fiddle](http://jsfiddle.net), it's pretty hard for us to guess at what the problem could be. Setting the value and triggering `chosen:updated` should work fine whether or not the content was loaded dynamically.

Closing the issue until more information is provided.

**Closed by pfiller** 2015-04-01 03:11 UTC

**Comment by vaikoovery** [comment] 2015-04-01 05:11
I hope the issue was known or self explanatory. Excuse for not providing fiddle link.

Here you go, https://jsfiddle.net/Vaishak/t5dtdg7s/

I've given two forms which explains both scenarios I had mentioned above.

**Comment by pfiller** [comment] 2015-04-02 22:51
Thanks for the update, @vaikoovery. I think your workaround is probably the best-case solution for the time being. The problem is Chosen is updating itself before the form field has reset. I tried some experiments listening for the form reset event, but it presents the same race condition.

Using a setTimeout with 0 will get you out of the reset event loop to always make sure Chosen is updating _after_ the field.

Thanks again for sharing. It's a weird one!

**Comment by vaikoovery** [comment] 2015-04-03 04:54
Thank you, @pfiller setting 0 timeout works in the given example, however I'm not sure if it affect in a form which has more fields, will it?

**Comment by pfiller** [comment] 2015-04-07 00:31
If a form has more than 1 Chosen field in it, you'll need to call update on all of them. The 0 timeout should still work as you'll be making sure the call happens after the form is reset.
