### ISSUE TITLE
Any way to get html inside the option tag to parse?

### ISSUE THREAD

**Issue by Jordan4jc** [harvesthq/chosen#2351] opened 2015-06-25 20:07 UTC
It would be super cool if I could say add a little image next to the text for each option, but if I put html code inside the options chosen doesn't parse it as actual html.

Is there a way to get this to work?

**Comment by tjschuck** [comment] 2015-06-25 20:09
Duplicate of https://github.com/harvesthq/chosen/pull/692 -- please leave any feedback you have there.  Thanks!

**Closed by tjschuck** 2015-06-25 20:09 UTC
