### ISSUE TITLE
IE scroller in chosen-results can be grabbed after result items have been added.

### ISSUE THREAD

**Issue by Kramb** [harvesthq/chosen#2927] opened 2017-12-01 19:49 UTC
### Summary

After the dropdown has been opened for the first time and is then closed, the vertical scrollbar is able to be grabbed without it actually displaying.

### Steps to reproduce

To reproduce this issue:

1. Create a select element with enough options to extend beyond the max-height of the chosen-results list.
2. Initialize the element as a chosen object.
3. Click the chosen container to trigger the dropdown event.
4. Click elsewhere to lose focus.
5. Click where the scrollbar **would** be located if the dropdown were open.

I have confirmed that this issue can be replicated on the chosen demo page in IE.
I have attempted to replicate this issue in Chrome, but was not able to.

### Expected behavior

After the element loses focus and the dropdown results have closed, a user should not be able to interact with the dropdown results or related elements.

### Actual behavior

User can interact with the scrollbar of the results after the dropdown has been closed.

### Environment

  - **Chosen Version**: 1.8.2

  - **jQuery or Prototype Version**: 1.9.1

  - **Browser and Version**: IE11

  - **OS and Version**: Windows 7 Enterprise Edition SP1 (64-bit)

**Comment by tjschuck** [comment] 2017-12-01 20:17
This is a duplicate of https://github.com/harvesthq/chosen/pull/2886 — please feel free to leave any additional feedback you have there.  Thanks!

**Closed by tjschuck** 2017-12-01 20:17 UTC
