### ISSUE TITLE
Can't detect container width if it is initially hidden.

### ISSUE THREAD

**Issue by ilyasovivan** [harvesthq/chosen#2984] opened 2018-05-22 17:31 UTC
Example: is in another tab on the page.
![Screencast](https://i.imgur.com/8fkeX54.gif)
Code:
`    AbstractChosen.prototype.container_width = function() {
      if (this.options.width != null) {
        return this.options.width;
      } else {
        return this.form_field.offsetWidth + "px";
      }
    };`

**Comment by tjschuck** [comment] 2018-05-22 18:05
I think this is a duplicate of https://github.com/harvesthq/chosen/issues/92 — closing this in favor of that.  Feel free to leave any additional feedback you have on that issue.

If this is truly a different issue, please let us know and we'll reopen.

**Closed by tjschuck** 2018-05-22 18:05 UTC
