### ISSUE TITLE
Chosen rendering issue within popup

### ISSUE THREAD

**Issue by Nazm** [harvesthq/chosen#2117] opened 2014-10-19 10:07 UTC
Can anyone help to make the div 'chosen-drop' on top of the popup?

![chosen is](https://cloud.githubusercontent.com/assets/747944/4692762/9d9ccbea-5777-11e4-8660-5233d2ed1fad.jpeg)

**Comment by pfiller** [comment] 2016-06-04 17:13
Duplicate of #86. There are lots of solutions discussed there.

**Closed by pfiller** 2016-06-04 17:13 UTC
