### ISSUE TITLE
Does not match if option text has "nbsp" before the text itself.

### ISSUE THREAD

**Issue by yahyaerturan** [harvesthq/chosen#2188] opened 2015-01-07 18:17 UTC
Hi, I have a little problem with my options which their text starts with "&nbsp". It can't match those items.
My Options are:

Home
Corporate
    Mission
    Vision
Products
Contact

It can match perfectly top level options. But it can't match "Mission" and "Vision" which has space before the text? How should I fix it?

**Comment by tjschuck** [comment] 2015-01-07 19:02
Duplicate of https://github.com/harvesthq/chosen/issues/2107 -- please leave any feedback you have there.

**Closed by tjschuck** 2015-01-07 19:02 UTC
