### ISSUE TITLE
When will Chosen be able to support Ajax remote request?

### ISSUE THREAD

**Issue by yswang0927** [harvesthq/chosen#2864] opened 2017-08-17 12:30 UTC
Ajax load data to Chosen is important. Just as [Select2](http://select2.github.io/)
When will Chosen be able to support Ajax remote request?

**Comment by stof** [comment] 2017-08-17 12:58
Well, if you want this feature, you could use Select2. Chosen is not meant to become a Select2 clone. Its goal is to enhance the UI of native selects, and these are not ajax-loaded.

Btw, if your goal is to lazy-load the options once (rather than performing server-side filtering when searching), this is *already* possible when using Chosen, by updating the options in the original `<select>` and then triggering the `chosen:updated` event on it (to tell Chosen than it should rebuild its list of options as the list changed)

**Comment by cooperfellows** [comment] 2017-08-17 13:56
I've used chosen successfully the way @stof is suggesting here. We load up several different select fields with options that are determined using an ajax request. Then trigger the `chosen:updated` event as suggested.

It works great this way.

**Comment by tjschuck** [comment] 2017-08-17 15:18
Like @stof and @cooperfellows said above, lazy loading is possible — just pull your data however you'd like, update the underlying `select`, and then `chosen:updated`.

If you meant fetching from a remote source on search, that's a duplicate of https://github.com/harvesthq/chosen/issues/79, and you should leave any additional feedback you have there.  (That said, that feature isn't likely to be added. As @stof said, that's outside the goals of Chosen.)

**Closed by tjschuck** 2017-08-17 15:18 UTC
