### ISSUE TITLE
Scrolling is rough

### ISSUE THREAD

**Issue by t9nick** [harvesthq/chosen#1818] opened 2014-03-10 17:43 UTC
Since the latest updates scrolling select lists seems to have a "snap-to-grid" effect. In other words it's not smooth scrolling. Jumps 4-5 options at a time. It is worse on FF than IE.

**Comment by tjschuck** [comment] 2016-02-22 19:56
The current version of [the Chosen homepage](http://harvesthq.github.io/chosen/) (running v1.5.1) no longer shows this issue for me in any browser I have, including latest Firefox.

I'm pretty sure there were no changes to Chosen made to fix this, so I'm assuming it was a Firefox bug that they have fixed in the meantime.

There's a new issue (#2543) that alleges something similar, but so far is irreproducible by me.

Since this issue _was_ reproducible once but no longer is, I'm going to close it.  If #2543 bears any fruit, we'll continue with that issue.

Thanks again for your report, @t9nick!

/cc @pfiller

**Closed by tjschuck** 2016-02-22 19:56 UTC
