### ISSUE TITLE
Could you find a way to customize options?

### ISSUE THREAD

**Issue by abazanvillanueva** [harvesthq/chosen#2441] opened 2015-10-07 05:12 UTC
Is there any way to make up the text displayed in options? for example, put de text in red, or maybe set an image.

**Comment by tjschuck** [comment] 2015-10-07 14:59
@abazanvillanueva All of the currently supported options are documented on [the options page](http://harvesthq.github.io/chosen/options.html).

As for your specific examples:

* **Making the text red:** you should be able to do this yourself with CSS.  If you need assistance with figuring that out, please post somewhere like [StackOverflow](http://stackoverflow.com/), using the [`chosen.js` tag](http://stackoverflow.com/questions/tagged/chosen.js).  You'll be more likely to get a quick answer there.  (The issue tracker is intended for bug reports and feature requests, not usage questions.)

* **Adding an image:** That's a duplicate of https://github.com/harvesthq/chosen/pull/2405 specifically, and https://github.com/harvesthq/chosen/pull/692 more generally.  Please leave any additional feedback you may have on those issues.

**Closed by tjschuck** 2015-10-07 14:59 UTC

**Comment by stof** [comment] 2015-10-07 15:28
@tjschuck are you sure about the tag name ? There is no such question on SO. Isn't it the [``jquery-chosen`` tag](http://stackoverflow.com/questions/tagged/jquery-chosen) instead ?

**Comment by tjschuck** [comment] 2015-10-07 15:32
@stof My tag has certainly worked historically, but you're right, it seems like it doesn't anymore :grimacing:  Will update!
