### ISSUE TITLE
chosen not working on latest chrome 64 dev

### ISSUE THREAD

**Issue by H3xx3n** [harvesthq/chosen#2921] opened 2017-11-09 14:36 UTC
Latest chrome seems to behave strangely on css clip property which is used extensively by chosen.

Clicking on the dropdown the values are not shown even if the "active" class is being set. If you try to remove and add the clip property from the Inspector, the results will show up

**Comment by tjschuck** [comment] 2017-11-13 23:23
Duplicate of https://github.com/harvesthq/chosen/issues/2816 — closing this in favor of that.

**Closed by tjschuck** 2017-11-13 23:23 UTC
