### ISSUE TITLE
Chosen not disabled in all android devices

### ISSUE THREAD

**Issue by afattahi54** [harvesthq/chosen#2239] opened 2015-02-18 09:33 UTC
I have test chosen on Android 4.4.2 with default browser and the "window.navigator.userAgent" returns : 

```
Mozila5/0(Linux; Android 4.4.2; SM_T705 Build/KOT49H) AppleWebKit/537.36(KHTML,like Gecko) Chrom/40.0.2214.109 Safari 537.36
```

As you can see the below if statment in chosen.jquery, will not be satisfied 

```javascript
if (/Android/i.test(window.navigator.userAgent)) {
        if (/Mobile/i.test(window.navigator.userAgent)) {
          return false;
        }
      }
```

I think the /Mobile/i.test(window.navigator.userAgent) should be removed :)

**Comment by tjschuck** [comment] 2015-02-18 15:56
@afattahi54 What device?  The reason the `Mobile` check is there is because Chosen is enabled by default on Android _tablets_, and we only intended to have it disabled on Android _phones_.

Closing pending more info.

**Closed by tjschuck** 2015-02-18 15:56 UTC

**Comment by afattahi54** [comment] 2015-02-20 13:01
Sorry for late reply. 
It is Samsung Tab S. Yes it is tablet, I thought that chosen will be disabled on Tablets too, It seems I was wrong :)

**Comment by tjschuck** [comment] 2015-02-20 16:27
@afattahi54 Thanks for clarifying!  Chosen is disabled by default on phone-ish devices just because it tends to not work well on their small screens, but on tablets, it generally has seemed to work well enough.

Did you have specific issues on the Tab S that made you want it to be disabled there?

**Comment by afattahi54** [comment] 2015-02-21 06:19
Well, the chosen needs to be clicked twice :( 

I try to explain it here :
1- When user clicks on the chosen, the chosen opens 
2- The chosen search input get the focus.
3- The tablet keyboard appears.
4- The chosen will  automatically. (I think the browser keyboard fires some events to make this or may be because the chosen lost focus) 
5- The user clicks on chosen again (with the tablet keyboard still open)
6- The chosen will works now.

This happens both on Samsung Tab and IPad 
You can test it with http://harvesthq.github.io/chosen/  too.
The above case will get worth if the maximum scale of view port is not set, the page will zoomed to a closed chosen.

I think the chosen should be disabled on tablets too :(

**Comment by tjschuck** [comment] 2015-02-23 18:41
@afattahi54 That's a known issue :(  See https://github.com/harvesthq/chosen/issues/2171 for more.

**Comment by asvetlenko** [comment] 2016-05-04 13:10
I have Sony Z4 Tablet with Android 6.0. and I try to use chosen drop-down, but unfortunately it is impossible because I cannot use scroll for chosen drop-down: You can try to reproduce this bug here: https://harvesthq.github.io/chosen/.
You should remover condition: if (/Mobile/i.test(window.navigator.userAgent))
