### ISSUE TITLE
Lazy load to chosen

### ISSUE THREAD

**Issue by 4nty** [harvesthq/chosen#1879] opened 2014-04-08 10:48 UTC
Good day,

I'm wondering about possibility to add a lazy-load to this awesome script, does anyone have any suggestions or code?

Best regards,
4nty

**Comment by BornALegend** [comment] 2015-01-23 18:54
Have you added the ability to apply lazy loading to the drop down list for chosen yet? It would probably work better if it constrained the search engine mechanism. Instead of allowing it to populate the list with all users in the db.

**Comment by pfiller** [comment] 2016-06-04 18:41
Duplicate of #79

**Closed by pfiller** 2016-06-04 18:41 UTC
