### ISSUE TITLE
Width 0px

### ISSUE THREAD

**Issue by pascalcarmoni** [harvesthq/chosen#2608] opened 2016-05-24 03:30 UTC
```
<script type="text/javascript">
    $(document).ready(function () {
        $(".chosen-select").chosen();
     
    });
</script>
```
In chrome : (ok in IE)
The width stay at 0px. I see all the option filled in but width still at 0px.

![image](https://cloud.githubusercontent.com/assets/6619173/15491427/3d77f996-213e-11e6-8b54-ec2b7ee6c8d8.png)

**Comment by pascalcarmoni** [comment] 2016-05-24 03:44
I need to fix with 

```
$(document).ready(function () {
    $(".chosen-select").chosen();
    $(".chosen-container").css("width", "100%");
    $(".search-field").find("input").css("width", $(".chosen-container").width());
});
```

**Comment by sp4m** [comment] 2016-05-24 10:21
Could you try to replicate the issue in a clean JSFiddle?

**Comment by pfiller** [comment] 2016-06-02 21:25
Duplicate of [so many issues](https://github.com/harvesthq/chosen/search?q=width+0&type=Issues&utf8=%E2%9C%93) ... Chosen has never done very well when the initial select is hidden and doesn't specify it's own width. An easy fix is to tell Chosen what its width should be:

```JavaScript
$("#some_select").chosen({width: 100%}});
```

**Closed by pfiller** 2016-06-02 21:25 UTC

**Comment by pascalcarmoni** [comment] 2016-06-05 17:07
not working

**Comment by proimage** [comment] 2018-12-02 20:38
> ```js
> $("#some_select").chosen( {width: "100%"} );
> ```

Fixed code, in case it helps anyone.
