### ISSUE TITLE
Non-sensitive Case Problem

### ISSUE THREAD

**Issue by EG3007** [harvesthq/chosen#2534] opened 2016-02-11 21:05 UTC
I am using Chosen 1.4.2 and it's realy so big problem for me the case-sensitive.
For example; when i start to type "ist" it's not finding the result "İSTANBUL" i have to write İSTANBUL to find. How can i fix it ? What should i do ?

**Comment by tjschuck** [comment] 2016-02-12 16:40
Chosen _is_ case insensitive already.  The problem is that its case insensitivity doesn't align with the Turkish alphabet — to Chosen (and more specifically, to JavaScript's regular expression engine), the capital of `i` is `I`, not `İ`.

Your issue is probably closer to https://github.com/harvesthq/chosen/issues/536.  Going to close this as a duplicate of that, but feel free to leave your feedback there.

Thanks for your report!

**Closed by tjschuck** 2016-02-12 16:40 UTC
