### ISSUE TITLE
Search for parameter problems

### ISSUE THREAD

**Issue by M7lrv** [harvesthq/chosen#2745] opened 2016-10-31 08:40 UTC
I would like to ask if the value of parameters to the option to search, then how allocation? The default option seems to be the text of the search.

**Comment by tjschuck** [comment] 2016-10-31 16:16
Sorry, @M7lrv, not sure I understand your question.  Can you clarify?

**Comment by M7lrv** [comment] 2016-11-01 01:08
I am in China, may not be very good in English, I am sorry. The problem is that the type of search box search can only be set to search only the option value attribute or name attribute?

**Comment by tjschuck** [comment] 2016-11-01 14:53
@M7lrv Ah, I understand now.  You're right — the only thing that is searched is the option's text, and there's no built-in way to change that currently.

"Searching by value" is another issue opened here: #800, so I'm going to close this as a duplicate of that one.

**Closed by tjschuck** 2016-11-01 14:53 UTC

**Comment by M7lrv** [comment] 2016-11-02 07:51
Do you want to update the version?
