### ISSUE TITLE
Toggle optgroup children

### ISSUE THREAD

**Issue by guit4eva** [harvesthq/chosen#2251] opened 2015-02-28 22:04 UTC
Is it possible to toggle the children of an optgroup when clicking on the optgroup label?

**Comment by tjschuck** [comment] 2015-03-02 17:09
Duplicate of https://github.com/harvesthq/chosen/issues/323 -- please leave any feedback you have there.  Thanks!

**Closed by tjschuck** 2015-03-02 17:09 UTC
