### ISSUE TITLE
Multiselect box typing keeps deselecting typing area.

### ISSUE THREAD

**Issue by HanaKana** [harvesthq/chosen#2476] opened 2015-11-16 03:12 UTC
https://github.com/harvesthq/chosen/issues/new

The issue can be seen on the default page.  Clicking on the box will select and enable typing but clicking again on any scroll area excluding the actual results (in IE and Chrome) will deselect the typing box area.

The typing box area will also be deselected in firefox when clicking on any area of the box over halfway to the right of the cursor point.

As when the box is deselected backspace will go back in the browser instead of deleting the text.

**Comment by 396708809** [comment] 2016-01-05 02:59
I have the same problem too.

**Comment by koenpunt** [comment] 2016-10-01 12:36
Duplicate of #1729

**Closed by koenpunt** 2016-10-01 12:36 UTC
