### ISSUE TITLE
Select / deselect all as last option

### ISSUE THREAD

**Issue by samuelrs** [harvesthq/chosen#2639] opened 2016-06-30 23:11 UTC
hello, I would like to know what I need to modify, so select all options, and deselect all, appear as last option in the list of options.

**Comment by tjschuck** [comment] 2016-07-01 18:45
This is not currently possible in Chosen — as a feature request, this is a duplicate of https://github.com/harvesthq/chosen/issues/1001.  Please leave any additional feedback you have there.  Thanks!

**Closed by tjschuck** 2016-07-01 18:45 UTC
