### ISSUE TITLE
Chosen Does not work in container which is on hidden state

### ISSUE THREAD

**Issue by hari-wac** [harvesthq/chosen#2920] opened 2017-11-08 13:20 UTC
Let we have a bootstrap modal and there is a select box inside that. If we call
`$('js-my-select-box').chosen()`, and then if I open the modal popup, we can see the chosen design has broken. We need to destroy the chosen box and again need to re initialize to work. The same happens in hidden blocks also. Do any have a better solution other than destroying and recreating?

Thanks,

**Comment by tjschuck** [comment] 2017-11-13 23:05
Pretty sure this is a duplicate of the long-standing https://github.com/harvesthq/chosen/issues/92.  Please feel free to leave any additional feedback you have there.  There's also a number of workarounds offered up on that issue.

**Closed by tjschuck** 2017-11-13 23:05 UTC
